== Cursive

Atualmente cursivo não suporta resolver as dependências através do `shadow-cljs.edn`. É possível rodar `shadow-cljs pom` para gerar um `pom.xml` e importar ele usando o IntelliJ.

Também é possível criar um `project.clj` ou usar <<Leiningen, Leiningen integration>>.

```
(defproject your/project "0.0.0"
  :dependencies
  [[thheller/shadow-cljs "X.Y.Z"]]

  :source-paths
  ["src"])
```

É possível rodar `npx shadow-cljs server` dentrodo terminal provido pelo IntelliJ e usar `Clojure REPL -> Remote` Run Configuration para se conectar ao <<nREPL, nREPL server>> fornecido.

== Emacs / CIDER [[cider]]

Essa sessão é escrita para versão do CIDER 0.20.0 e acima. Tenha certeza que seu Emacs possui a versão do pacote `cider` mais recente. Referências no link:https://docs.cider.mx[CIDER documentation] para instalação completa.


=== Launch o ClojureScript REPL

Launch o nREPL e um ClojureScript REPL.

```console
M-x cider-jack-in-cljs
```

CIDER vai abrir um prompt para que você digite o tipo de ClojureScript REPL:

```console
Select ClojureScript REPL type:
```

Digite `shadow`.

```console
Select shadow-cljs build:
```

Digite o nome do seu build target, por exemplo `app`.

Emacs deveria abrir uma nova conexão nREPL para o servidor `shadow-cljs`servido de seu irmão, transformando em um ClojureScript REPL:

```console
shadow.user> To quit, type: :cljs/quit
[:selected :app]
cljs.repl>
```

Agora você deve ser capaz de avaliar ClojureScript, pulando para as definições de variáveis (com `cide-find-var`) e muito mais.

Por exemplo, tente exibit um alerta no navegador:

```console
cljs.repl> (js/alert "Jurassic Park!")
```

=== Simplificando inicialização com dir-local

É possível simplificar o fluxo inicialização criando um arquivo `.dir-locals.el` na ráiz do projeto.

```
((nil . ((cider-default-cljs-repl . shadow)
	 (cider-shadow-default-options . "<your-build-name-here>"))))
```

== Proto REPL (Atom)

Proto REPL é principalmente destinado ao desenvolvimento Clojure então a maria das funcionalidades não funciona para ClojureScript. No entando é possível usa-las para avalições simples.

É preciso configurar um conjunto de coisas para isso funcionar

1) Crie um `user.clj` no `:source-paths`.

```clojure
 (ns user)

 (defn reset [])
```

O arquivo deve definir a fn `user/rest` do qual Proto REPL irá chamar quando conectando. Se `user/reset` não for encontrada isso irá chamar `tools.namespace` do qual destroi o servidor `shadow-cljs` que estiver rodando. Não queremos isso. Você poderia fazer alguma coisa aqui mas não queremos fazer nada para CLJS.

2) adicione `[proto-repl "0.3.1"]` para sua `:dependencies` em <<user-config, ~/.shadow-cljs/config.edn>> ou `shadow-cljs.edn`.

3) Configura uma porta fixa <<nREPL, nREPL port>>

4) Inicie `shadow-cljs server` ou `shadow-cljs watch your-build`.

5) Rode o comando Atom `Proto Repl: Remote Nrepl Connection` para se conectar ao `localhost` e a porta que você configurou

6) Avalie `(shadow.cljs.devtools.api/watch :your-build)` (se você usou `server` no passo 4)

7) Avalie `(shadow.cljs.devtools.api/nrepl-select :your-build)`. A conexão REPL está agora conectada no modo CLJS, significando que tudo que você avalia será avaliado em JS. É possível avaliar `:repl/quit` para voltar ao modo Clojure. Se por acaso aparecer `[:no-worker :browser]` você precisa iniciar o `watch` antes.

8) Antes que você consiga avaliar CLJS você precisa conectar ao seu cliente (ex.: quando seu browser estiver construindo um App `:browser`).

9) Avalie algo em JS, ex.: `(js/alert "foo")`. Se por acaso aparecer `There is no connected JS runtime` o cliente não está conectado adequadamente. De outro modo o navegador deveria mostrar um alerta.

== Chlorine (Atom)

Chlorine conecta Atom a um Socket REPL, mas também tenta atualizar o namespace. Então primeira, abra o pacote de configuração Chlorine e verifique se a configuração `Should we use clojure.tools.namespace to refresh` está setada como `simple`, de outro modo isso vai ser destruido quando rodando um servidor `shadow-cljs`.

Uma vez verifica que a configuração está correta, é possível começar seu app shadow (substitua `app` por qualquer build):

```
$ shadow-cljs watch app
```

Agora tudo que você tem que fazer é rodar o comando atom `Chlorine: Connect Clojure Socket Repl`. Isso irá conectar a REPL para avaliar código Clojure. No próximo passo você vai precisar rodar `Chlorine: Connect Embeded`, e isso vai conectar o ClojureScript ao REPL também.

Agora, é possível usar o comando `Chlorine: Evaluate...` para avaliar qualquer Clojure ou ClojureScript REPL. Isso vai avaliar os arquivos `.clj` como Clojure, e os arquivos `cljc` como ClojureScript.

== Calva (VS Code)

(Testado apenas com o target `browser` por enquanto. Provavelmente vai funcionar com outros targets também.)

=== Dependências

Você precisa de VS Code a da extensão https://marketplace.visualstudio.com/items?itemName=cospaia.clojure4vscode#overview[Calva].

Desde que o Calva use nREPL e o middleware `cider-nrepl` é necessário incluir essa dependência no <<user-config, ~/.shadow-cljs/config.edn>> ou `shadow-cljs.edn`:

```clojure
[cider/cider-nrepl "0.21.0"]
```

`shadow-cljs` ira injetar o middleware requqerido `cider-nrepl` uma vez que ele exergue essa dependência.

=== Conectando Calva as REPLs

Uma vez feito inicie seu shadow app. (Usando qualquer build ao invés do `app.`):

```
$ shadow-cljs watch app
```

Uma vez que o app é carregado no navegador, e seja visível `JS runtime connected` no terminal onde você iniciou o app, Calva consegue se conectar a essa repl. Abra o projeto no VS Code e Calva vai conectar por padrão tentando se auto conectar e solicitar uma lista de builds de leitura a partir do `shadow-cljs.edn`. Selecione o correto (`:app` nesse exemplo) e o suporte Calva para Clojure e ClojureScript é ativado.

(Se você já tem o projeto aberto no VS Code quando iniciando o app, issue emita o comando `clojure4vscode: connect`.)

=== Funcionalidades

Alguma das coisas que você pode fazer agora:

==== Intellisense

- Observar as definições no hover.
- Ajuda de auto-complete.
- Navegar para as definições (`cmd-click` no Mac, deve ser `ctrl-click` no Windows e Linux).

==== Avaliação de arquivos, forms e seleção

- Avalie o arquivo: `ctrl+alt+c ender` (Isso é feito automáticamente ao abrir arquivos.)
- Avalie inline: `ctrl+alt+c e`
- Avalie e substitua eles no editor: `ctrl+alt+c r`
- Pretty print avaliando resultados `ctrl+alt+c p`
- Envia forms para o repls terminal integrado para avaliação : `ctrl+alt+c alt+e`

==== Rodando testes

- Rode namespace testes: `ctrl+alt+c t`
- Rode todos os testes: `ctrl+alt+c shift+t`
- Rodar novamente os testes que estão falhando: `ctrl+alt+c ctrl+t`
- Testes falhando são marcado no explorer and editor e listado na tab de problemas para fácil acesso

==== Terminal repls

- Troque de namespace no terminal da repl para o arquivo aberto: `ctrl+alt+c n`
- Carregue o arquivo atual e troque o namespace: `ctrl+alt+c alt+n`

==== Arquivos Cljc

- Troque entre as repls Clojure e Clojurescript `ctrl+alt+c ctrl+alt+t` (ou clique no botão verde `cljc/clj` na  barra de status). Ela determina tanto qual a repl do editor como qual terminal repl está sendo acessado, veja abaixo.  

== Fireplace.vim (Vim/Neovim)

https://www.vim.org/scripts/script.php?script_id=4978[Fireplace.vim] é um Vim/Neovim plug-in que fornece uma integração ao Clojure REPL agindo como um cliente https://nrepl.org/[nREPL]. Quando combinado com Shadow-CLJS, também fornece uma integração ClojureScript REPL.

Esse guia usa um exemplo, uma aplicação criada no guia oficial https://github.com/thheller/shadow-cljs#quick-start[Shadow-CLJS Quick Start] portanto refere-se a poucos itens de configuração no app's `shadow-cljs.edn`. Como dito, esses items de configuração são bastante genéricos então deveriam ser aplicados para outros apps com poucas modificações. 

=== Dependências

Instale https://www.vim.org/scripts/script.php?script_id=4978[Fireplace.vim] usando seu método de instalação favorito Vim/Neovim.

Como um cliente https://nrepl.org/[nREPL], https://www.vim.org/scripts/script.php?script_id=4978[Fireplace.vim] depende de https://docs.cider.mx/cider-nrepl/[CIDER-nREPL] (que é um middleware nREPL que provê comum, operações editor-agnostic REPL) portando você precisa incluir essas dependências no <<user-config, ~/.shadow-cljs/config.edn>> ou `shadow-cljs.edn` (como mostra a próxima sub-sessão) Shadow-CLJS vai injetar o middleware obrigatório CIDER-nREPL uma vez que ele vê essa dependência.

=== Preparando o app

Crie um exemplo de app seguindo guia oficial https://github.com/thheller/shadow-cljs#quick-start[Shadow-CLJS Quick Start] e modifique o `shadow-cljs.edn` como o seguinte:

```clojure
;; shadow-cljs configuração
{:source-paths
 ["src/dev"
  "src/main"
  "src/test"]

 ;; Adicione - CIDER-nREPL middleware requerido pelo Fireplace.vim
 :dependencies
 [[cider/cider-nrepl "0.22.4"]]

 ;; Adicione - uma porta (e.x., 3333) para o servidor REPL do qual o Fireplace.vim vai se conectar
 :nrepl
 {:port 3333}

 ;; Adicione - uma porta (e.x., 8080) para o servidor HTTP development-time que fornece o app
 :dev-http
 {8080 "public"}

 :builds
 {:frontend  ; OBS - Esse é o build ID referenciado por vários lugares abaixo.
  {:target :browser
   :modules {:main {:init-fn acme.frontend.app/init}}}}}
```

Uma vez isso feito, inicie o app (perceba que o build ID Shadow-CLJS, `frontend`, especificado em `shadow-cljs.edn`):

```sh
npx shadow-cljs watch frontend
```

Abra o app no navegador em http://localhost:8080/. Sem esse passo, você iria capturar a seguinte mensagem de error https://www.vim.org/scripts/script.php?script_id=4978[Fireplace.vim] se você tentar se conectar ao servidor REPL de dentro do Vim/Neovim:

```
No application has connected to the REPL server. 
Make sure your JS environment has loaded your compiled ClojureScript code.
```

=== Conectando Fireplace.vim ao servidor REPL

Abra o arquivo fonte ClojureScript no Vim/Neovim e execute o seguinte comando para conectar https://www.vim.org/scripts/script.php?script_id=4978[Fireplace.vim] ao servidor REPL (perceba a prota para o servidor REPL, `3333`, especificado em `shadow-cljs.edn`):

```
:Connect 3333
=>
Connected to nrepl://localhost:3333/                                                              
Scope connection to: ~/code/clojurescript/acme-app (ENTER)
```

Isso cria uma sessão Clojure no REPL (ao invés de ClojureScript). Execute o seguinte comando para adicionar suporte ao ClojureScript para a sessão (perceba o shadow-cljs build id, `frontend`, especificado em `shadow-cljs.edn`):

```
:CljEval (shadow/repl :frontend)
=>
To quit, type: :cljs/quit                                                                      
[:selected :frontend]
Press ENTER or type command to continue
```

Agora você consegue executar os comandos diante do servidor REPL https://www.vim.org/scripts/script.php?script_id=4978[Fireplace.vim]. Por favor recorra a documentação https://www.vim.org/scripts/script.php?script_id=4978[Fireplace.vim] para a lista completa de comando que você quer executar.
