== Cursive

Atualmente cursivo não suporta resolver as dependências através do `shadow-cljs.edn`. É possível rodar `shadow-cljs pom` para gerar um `pom.xml` e importar ele usando o IntelliJ.

Também é possível criar um `project.clj` ou usar <<Leiningen, Leiningen integration>>.

```
(defproject your/project "0.0.0"
  :dependencies
  [[thheller/shadow-cljs "X.Y.Z"]]

  :source-paths
  ["src"])
```

É possível rodar `npx shadow-cljs server` dentrodo terminal provido pelo IntelliJ e usar `Clojure REPL -> Remote` Run Configuration para se conectar ao <<nREPL, nREPL server>> fornecido.

== Emacs / CIDER [[cider]]

Essa sessão é escrita para versão do CIDER 0.20.0 e acima. Tenha certeza que seu Emacs possui a versão do pacote `cider` mais recente. Referências no link:https://docs.cider.mx[CIDER documentation] para instalação completa.


=== Launch o ClojureScript REPL

Launch o nREPL e um ClojureScript REPL.

```console
M-x cider-jack-in-cljs
```

CIDER vai abrir um prompt para que você digite o tipo de ClojureScript REPL:

```console
Select ClojureScript REPL type:
```

Digite `shadow`.

```console
Select shadow-cljs build:
```

Digite o nome do seu build target, por exemplo `app`.

Emacs deveria abrir uma nova conexão nREPL para o servidor `shadow-cljs`servido de seu irmão, transformando em um ClojureScript REPL:

```console
shadow.user> To quit, type: :cljs/quit
[:selected :app]
cljs.repl>
```

Agora você deve ser capaz de avaliar ClojureScript, pulando para as definições de variáveis (com `cide-find-var`) e muito mais.

Por exemplo, tente exibit um alerta no navegador:

```console
cljs.repl> (js/alert "Jurassic Park!")
```

=== Simplificando inicialização com dir-local

É possível simplificar o fluxo inicialização criando um arquivo `.dir-locals.el` na ráiz do projeto.

```
((nil . ((cider-default-cljs-repl . shadow)
	 (cider-shadow-default-options . "<your-build-name-here>"))))
```

== Proto REPL (Atom)

Proto REPL é principalmente destinado ao desenvolvimento Clojure então a maria das funcionalidades não funciona para ClojureScript. No entando é possível usa-las para avalições simples.

É preciso configurar um conjunto de coisas para isso funcionar

1) Crie um `user.clj` no `:source-paths`.

```clojure
 (ns user)

 (defn reset [])
```

O arquivo deve definir a fn `user/rest` do qual Proto REPL irá chamar quando conectando. Se `user/reset` não for encontrada isso irá chamar `tools.namespace` do qual destroi o servidor `shadow-cljs` que estiver rodando. Não queremos isso. Você poderia fazer alguma coisa aqui mas não queremos fazer nada para CLJS.

2) adicione `[proto-repl "0.3.1"]` para sua `:dependencies` em <<user-config, ~/.shadow-cljs/config.edn>> ou `shadow-cljs.edn`.

3) Configura uma porta fixa <<nREPL, nREPL port>>

4) Inicie `shadow-cljs server` ou `shadow-cljs watch your-build`.

5) Rode o comando Atom `Proto Repl: Remote Nrepl Connection` para se conectar ao `localhost` e a porta que você configurou

6) Avalie `(shadow.cljs.devtools.api/watch :your-build)` (se você usou `server` no passo 4)

7) Avalie `(shadow.cljs.devtools.api/nrepl-select :your-build)`. A conexão REPL está agora conectada no modo CLJS, significando que tudo que você avalia será avaliado em JS. É possível avaliar `:repl/quit` para voltar ao modo Clojure. Se por acaso aparecer `[:no-worker :browser]` você precisa iniciar o `watch` antes.

8) Antes que você consiga avaliar CLJS você precisa conectar ao seu cliente (ex.: quando seu browser estiver construindo um App `:browser`).

9) Avalie algo em JS, ex.: `(js/alert "foo")`. Se por acaso aparecer `There is no connected JS runtime` o cliente não está conectado adequadamente. De outro modo o navegador deveria mostrar um alerta.

== Chlorine (Atom)

Chlorine conecta Atom a um Socket REPL, mas também tenta atualizar o namespace. Então primeira, abra o pacote de configuração Chlorine e verifique se a configuração `Should we use clojure.tools.namespace to refresh` está setada como `simple`, de outro modo isso vai ser destruido quando rodando um servidor `shadow-cljs`.

Uma vez verifica que a configuração está correta, é possível começar seu app shadow (substitua `app` por qualquer build):

```
$ shadow-cljs watch app
```

Agora tudo que você tem que fazer é rodar o comando atom `Chlorine: Connect Clojure Socket Repl`. Isso irá conectar a REPL para avaliar código Clojure. No próximo passo você vai precisar rodar `Chlorine: Connect Embeded`, e isso vai conectar o ClojureScript ao REPL também.

Agora, é possível usar o comando `Chlorine: Evaluate...` para avaliar qualquer Clojure ou ClojureScript REPL. Isso vai avaliar os arquivos `.clj` como Clojure, e os arquivos `cljc` como ClojureScript.

== Calva (VS Code)

(Testado apenas com o target `browser` por enquanto. Provavelmente vai funcionar com outros targets também.)

=== Dependências

Você precisa de VS Code a da extensão https://marketplace.visualstudio.com/items?itemName=cospaia.clojure4vscode#overview[Calva].

Desde que o Calva use nREPL e o middleware `cider-nrepl` é necessário incluir essa dependência no <<user-config, ~/.shadow-cljs/config.edn>> ou `shadow-cljs.edn`:

```clojure
[cider/cider-nrepl "0.21.0"]
```

`shadow-cljs` ira injetar o middleware requqerido `cider-nrepl` uma vez que ele exergue essa dependência.

=== Conectando Calva as REPLs

Uma vez feito inicie seu shadow app. (Usando qualquer build ao invés do `app.`):

```
$ shadow-cljs watch app
```

Uma vez que o app é carregado no navegador, e seja visível `JS runtime connected` no terminal onde você iniciou o app, Calva consegue se conectar a essa repl. Abra o projeto no VS Code e Calva vai conectar por padrão tentando se auto conectar e solicitar uma lista de builds de leitura a partir do `shadow-cljs.edn`. Selecione o correto (`:app` nesse exemplo) e o suporte Calva para Clojure e ClojureScript é ativado.

(Se você já tem o projeto aberto no VS Code quando iniciando o app, issue emita o comando `clojure4vscode: connect`.)

=== Funcionalidades

Alguma das coisas que você pode fazer agora:

==== Intellisense

- Observar as definições no hover.
- Ajuda de auto-complete.
- Navegar para as definições (`cmd-click` no Mac, deve ser `ctrl-click` no Windows e Linux).

==== Avaliação de arquivos, forms e seleção

- Avalie o arquivo: `ctrl+alt+c ender` (Isso é feito automáticamente ao abrir arquivos.)
- Avalie inline: `ctrl+alt+c e`
- Avalie e substitua eles no editor: `ctrl+alt+c r`
- Pretty print avaliando resultados `ctrl+alt+c p`
- Envia forms para o repls terminal integrado para avaliação : `ctrl+alt+c alt+e`

==== Rodando testes

- Rode namespace testes: `ctrl+alt+c t`
- Rode todos os testes: `ctrl+alt+c shift+t`
- Rodar novamente os testes que estão falhando: `ctrl+alt+c ctrl+t`
- Testes falhando são marcado no explorer and editor e listado na tab de problemas para fácil acesso

==== Terminal repls

- Switch namespace in terminal repl to that of the currently open file: `ctrl+alt+c n`
- Load current file and switch namespace in: `ctrl+alt+c alt+n`

==== Cljc files

- Switch between Clojure and Clojurescript repl `ctrl+alt+c ctrl+alt+t` (or click the green `cljc/clj` button in the status bar). This determines both which repl is backing the editor and what terminal repl is being accessed, see above.

== Fireplace.vim (Vim/Neovim)

https://www.vim.org/scripts/script.php?script_id=4978[Fireplace.vim] is a Vim/Neovim plug-in which provides Clojure REPL integration by acting as an https://nrepl.org/[nREPL] client. When combined with Shadow-CLJS, it also provides ClojureScript REPL integration.

This guide uses as an example the app created in the official https://github.com/thheller/shadow-cljs#quick-start[Shadow-CLJS Quick Start] guide therefore refers to a few configuration items in the app's `shadow-cljs.edn`. That being said, these configuration items are fairly generic so should be applicable to other apps with minor modifications.

=== Dependencies

Install https://www.vim.org/scripts/script.php?script_id=4978[Fireplace.vim] using your favorite method of installing plug-ins in Vim/Neovim.

As an https://nrepl.org/[nREPL] client, https://www.vim.org/scripts/script.php?script_id=4978[Fireplace.vim] depends on https://docs.cider.mx/cider-nrepl/[CIDER-nREPL] (which is nREPL middleware that provides common, editor-agnostic REPL operations) therefore you need to include this dependency in <<user-config, ~/.shadow-cljs/config.edn>> or `shadow-cljs.edn` (as shown in the next sub-section.) Shadow-CLJS will inject the required CIDER-nREPL middleware once it sees this dependency.

=== Preparing the app

Create the example app by following the official https://github.com/thheller/shadow-cljs#quick-start[Shadow-CLJS Quick Start] guide and modify its `shadow-cljs.edn` as follows:

```clojure
;; shadow-cljs configuration
{:source-paths
 ["src/dev"
  "src/main"
  "src/test"]

 ;; ADD - CIDER-nREPL middleware required by Fireplace.vim
 :dependencies
 [[cider/cider-nrepl "0.22.4"]]

 ;; ADD - a port (e.g., 3333) for the REPL server to which Fireplace.vim connects
 :nrepl
 {:port 3333}

 ;; ADD - a port (e.g., 8080) for the development-time HTTP server that serves the app
 :dev-http
 {8080 "public"}

 :builds
 {:frontend  ; NOTE - This is the build ID referenced at various places below.
  {:target :browser
   :modules {:main {:init-fn acme.frontend.app/init}}}}}
```

Once that is done, start the app (note the Shadow-CLJS build ID, `frontend`, specified in `shadow-cljs.edn`):

```sh
npx shadow-cljs watch frontend
```

Open the app in a browser at http://localhost:8080/. Without this step, you would get the following error message from https://www.vim.org/scripts/script.php?script_id=4978[Fireplace.vim] if you attempt to connect to the REPL server from within Vim/Neovim:

```
No application has connected to the REPL server. 
Make sure your JS environment has loaded your compiled ClojureScript code.
```

=== Connecting Fireplace.vim to REPL Server

Open a ClojureScript source file in Vim/Neovim and execute the following command to connect https://www.vim.org/scripts/script.php?script_id=4978[Fireplace.vim] to the REPL server (note the port for the REPL server, `3333`, specified in `shadow-cljs.edn`):

```
:Connect 3333
=>
Connected to nrepl://localhost:3333/                                                              
Scope connection to: ~/code/clojurescript/acme-app (ENTER)
```

This creates a Clojure (instead of ClojureScript) REPL session. Execute the following command to add ClojureScript support to the session (note the Shadow-CLJS build ID, `frontend`, specified in `shadow-cljs.edn`):

```
:CljEval (shadow/repl :frontend)
=>
To quit, type: :cljs/quit                                                                      
[:selected :frontend]
Press ENTER or type command to continue
```

You should now be able to execute https://www.vim.org/scripts/script.php?script_id=4978[Fireplace.vim] commands against the REPL server. Please refer to the https://www.vim.org/scripts/script.php?script_id=4978[Fireplace.vim] documentation for the full list of commands you can execute.
