= Introdução

`shadow-cljs` provê tudo que você precisa pra compilar seu projeto ClojureScript com foco em simplicidade e facilidade de uso. A compilação do build fornecidos abstraem a maioria da configuração manual de modo que a única coisa que você tem que fazaer é configurar coisas essenciais para o seu build. Cada target provê padrões ótimos para cada ambiente e fornece uma experiência otimizada durante a fase de desenvolvimento e builds de produção.

== Visão de auto nível

`shadow-cljs` é composto de duas partes:

- A https://clojars.org/thheller/shadow-cljs[shadow-cljs] biblioteca Clojure que manipula todo o trabalho atual.
- O https://www.npmjs.com/package/shadow-cljs[shadow-cljs], pacote `npm` que fornece uma interface coviciente para rodar a maioria das funcionalidades de build diretamente da linha de comando.

É possivel integrar facilmente a biblioteca Clojure `shadow-cljs` em qualquer outro ferramenta de compilação Clojure/JVM (eg. https://leiningen.org/[leiningen] ou a ferramenta https://clojure.org/guides/deps_and_cli[Clojure CLI]).

É recomendado usar os pacotes `npm` que fornece uma experiência mais otimizada e sob medida em relação ao desenvolvimento com CLJS.

== Fluxo de trabalho básico 

When trabalhando com `shadow-cljs` você definirá uma ou mais builds no arquivo de configuração `shadow-cljs.edn`. Cada build tem a propriedade `:target` que representa uma configuração otimizada e predefinida para o ambiente alvo (eg. the Browser, uma aplicação `node.js` ou uma Extensão Chrome).

Cada buila pode produzir uma saída de desenvolvimento ou de produção dependendo do comando usado para disparar a compilação. Os padrões de build são: `compile`, `watch` e `release`.

=== Modo de desenvolvimento

É possível `compile` uma build de desenvolvimento uma vez ou rodar o processo `watch` que vai monitorar seus arquivos e recompilar eles automáticamente (e live-reload o code se você desejar).

Todas as builds de desenvolvimento são otimizadas para experiência do desenvolvedor, com ciclos de feedback rápido e outras funcionalidades como REPL para interagir diretamente com o código rodando.

Uma build de desenvolvimento nunca deveria ser públicada desde que ela pode torna-se um pouco grande e deve funcionar apenas na máquina onde foi compilada, dependendo do `:target`.

=== Modo de produção

Criando uma build de `release` vai remover todo o código relacionado ao modo de desenvolvimento e finalmente roda o código atráves do Closure Compiler. Esse é um Compiler otimizado para JavaScript que reduz significativamente no geral o tamanho do código.


== Conceitos importantes

Existe vários conceitos importantes que você deveria estar familiarizado quando usando `shadow-cljs`. Eles são fundamentais para o entendimento de como tudo se encaixa junto e como a ferramenta trabalha com o código.

=== O Classpath

`shadow-cljs` usa a Java Virtual Machine (JVM) e o "classpath" quando trabalhando com arquivos. Esse é o filesystem virtual composto de muitas entidades classpath. Cada entidade é

- O diretório filesystem local, gerenciado pela entidade `:source-paths` na configuração.
- Ou o arquivo `.jar`, representando Clojure(Script) ou bibliotecas JVM. Esses são arquivos comprimidos contento muitos arquivos (basicamente apenas um arquivo `.zip`). Esses são adicionados pelo `:dependencies`.

Em um projeto Clojure(Script) tudo é um namespace e cada nome representa um arquivo. Se existe um namespace `(ns demo.app)` o compilador espera encontra um `demo/app.cljs` (ou `cljs`) no classpath. O classpath será procurado em ordem até ser encontrado. Supnha que o `:source-paths` foi configurado da seguinte maneira ["src/main" "src/test"] o compilador vai procurar primeiro por um `src/main/demoi/app.cljs` e então `src/test/demo.app.cljs`. Quando o arquivo não é encontrado em nenhum source path a JVM vai começar a procurar dentro dos arquivos `.jar` no classpath. Quando encontra um `demo/app.cljs` na raíz de qualquer biblioteca o arquivo será usado.

IMPORTANTE: Quando o nome do arquivo existe múltiplas vezes no classpath então apenas o primeiro é usado. Tudo na JVM e Clojure(Script) é namespaced para evitar quaisquer conflitos. Muito similar ao `npm` onde cada pacote deve ter um nome único.

É portanto recomendado ser bem disciplinado quanto a escolha dos nomes e aplicar namespace em tudo. Deve parecer repetitivo sempre usar `(ns your-company.components.foo)` ao invés de `(ns components.foo)` porém esse detalhe vai evitar um monte de dor de cabeça no futuro.

É o contrário do `npm` onde o nome dos pacotes nunca é usado dentro do pacote em si e apenas relativo aos paths usados.


=== Modo de Servidor

`shadow-cljs` pode ser iniciado em um modo de "servidor" do qual é requerido para tarefas long-running tal como `watch`. Um `watch` vai implicitamente começar uma instância se já não estiver rodando. O servidor prover um endpoint Websocket que vai se conectar assim como todos os outros endpoints para nREPL, Socket REPL e o desenvolvimento de HTTP servers.

Quando usando o CLI do `shadow-cljs` todos os comandos são resusáveis rodando em uma instância do servidor da JVM ao invês de iniciar uma nova JVM. Isso é substancialmente rápido desde que o tempo start-up pode ser um pouco lento.

Uma vez o servidor rodando contudo, só vai ser preciso reiniciar apenas quando mudar o `:dependencies` e tudo mais pode ser feito via REPL.

=== REPL

O REPL é o coração de todo o desenvolvimento CLojure(Script) e cada comando do CLI pode ser usando diretamente do REPL. E vale muito a pena se sentir confortável com o REPL mesmo se a linha de comando parecer mais familiar.
