== NPM [[npm]]

https://www.npmjs.com/[npm] tem se tornado o package manager padrão para JavaScript. Quase todas as bibliotecas JS podem ser encontradas lá e o shadow-cljs provê uma integração desatada para acesssar esses packages.

=== Usando npm packages

Muito dos pacotes npm irão incluir algumas instruções em como usar o código atual. O "old" estilo CommonJS só precisa de chamadas do qual traduz diretamente:

```js
var react = require("react");
```

```
(ns my.app
  (:require ["react" :as react]))
```

Tanto faz o parâmetro "string" usado quando chamando require nos transferimos para o `:require` as-is. O apelido `:as` cabe a você. Uma vez que nós temos isso, podemos usar o código como qualquer outro namespace CLJS!

```
(react/createElement "div" nil "hello world")
```

No `shadow-cljs`: *sempre usa o `ns` from e tanto faz o apelido `:as` que você forneceu.* Você deve também usar `:refer` e `:rename`. Isso é diferente do que `:foreign-libs`/CLJSJS faz onde você inclui a coisa no namespace mas então usa um global `js/Thing` no seu código.

Alguns pacotes penas exporta uma única função da qual você chama diretamente usando `(:require ["thing" :as thing])` e então `(thing)`.

Mais recentemente alguns pacotes começam usando ES6 a declarção `import` em seus exemplos. Esses também são muito bem traduzidos 1:1 com uma pequena diferença relacionada ao export padrão.

A seguinte tabela pode ser usada para trandução:

IMPORTANTE: Essa tabela apenas se aplica se o código que você está rodando consome o pacote como um código ES6+. Se o código do pacote é um CommonJS o `:default` não deve ser aplicado. Veja a sessão abaixo para mais informações.

.ES6 import para CLJS
|===
|ES6 Import|CLJS Require

|`import defaultExport from "module-name";`
|`(:require ["module-name" :default defaultExport])`

|`import * as name from "module-name";`
|`(:require ["module-name" :as name])`

|`import { export } from "module-name";`
|`(:require ["module-name" :refer (export)])`

|`import { export as alias } from "module-name";`
|`(:require ["module-name" :rename {export alias}])`

|`import { export1 , export2 } from "module-name";`
|`(:require ["module-name" :refer (export1 export2)])`

|`import { export1 , export2 as alias2 , [...] } from "module-name";`
|`(:require ["module-name" :refer (export1) :rename {export2 alias2}])`

|`import defaultExport, { export [ , [...] ] } from "module-name";`
|`(:require ["module-name" :refer (export) :default defaultExport])`

|`import defaultExport, * as name from "module-name";`
|`(:require ["module-name" :as name :default defaultExport])`

|`import "module-name";`
|`(:require ["module-name"])`
|===

Perceba que anteriormente estavamos presos usando um bunde do qual incluia um monte de código que atualmente não é preciso. Agora estamos em uma situação melhor: Agumas bibliotecas estão empacotadas em uma maneira que permite que você inclue apenas as partes necessárias, levando a muito menos código no build final.

`react-virtualized` is a great example:

```js
// You can import any component you want as a named export from 'react-virtualized', eg
import { Column, Table } from 'react-virtualized'

// But if you only use a few react-virtualized components,
// And you're concerned about increasing your application's bundle size,
// You can directly import only the components you need, like so:
import AutoSizer from 'react-virtualized/dist/commonjs/AutoSizer'
import List from 'react-virtualized/dist/commonjs/List'
```

Com nossa melhoria de suporte podemos facilmente traduzir em:

```
(ns my-ns
  ;; all
  (:require ["react-virtualized" :refer (Column Table)])
  ;; OR one by one
  (:require ["react-virtualized/dist/commonjs/AutoSizer" :default virtual-auto-sizer]
            ["react-virtualized/dist/commonjs/List" :default virtual-list]))
```

==== Sobre :default Exports

A opção `:default` é atualmente apenas disponível com `shadow-cljs`, você pode https://dev.clojure.org/jira/browse/CLJS-2376[votar aqui] para esperançosamente tornar isso um padrão. Mas você pode sempre usar `:as alias` e então chamar `alias/default` se você preferir ficar totalmente compatível com o padrão CLJS.

Default exports são um acrescimo ao módules ECMAScript e não existe no código CommonJS. Algumas vezes você vai ver exemplos de `import Foo from "something"` quando o código é na verdade um código CommonJS. Nesses casos `(:require ["something" :default Foo])` não vai funcionar e invés disso `(:require ["something" :as Foo])` deve ser usado.

Se o `:require` não estiver funcionando da maneira esperada é recomendado tentar olhar ele na REPL.

```
$ shadow-cljs browser-repl (or node-repl)
...
[1:1]~cljs.user=> (require '["react-tooltip" :as x])
nil
[1:1]~cljs.user=> x
#object[e]
[1:1]~cljs.user=> (goog/typeOf x)
"function"
[1:1]~cljs.user=> (js/console.dir x)
nil
```

Desde que printar objetos JS nem sempre é útil (como visto acima) é possível usar `(js/console.dir x)` para conseguir uma representação mais útil no console do navegador. `goog/typeOf` também deve ser útil as vezes. Desde que o exemplo acima mostra `"function"` usando `:default` não deveria funcionar uma vez que o `:default` é basicamente uma syntax sugar para `x/default`.

=== Package Provider [[js-provider]]

`shadow-cljs` suporta diversas maneiras diferentes de incluir pacotes `npm` no seu build. Eles são configurados através das configurações `:js-options :js-provider`. Cada `:target` geralmente define aquele apropriado para seu build, na maioria das vezes você não vai precisar tocar nessa configuração.

Atualmente são suportados três providers:

[Horizontal]
`:require`:: Mapeado diretamente para a chamada de função JS `require("thing")`. É o padrão para todos os alvos `node.js` uma vez que ele pode resolver `require` nativamente em tempo de execução. O JS incluido não é processado de nenhuma maneira.
`:shadow`:: Resolve o JS através do `node_modules` e inclui uma versão minificada para cada arquivo referênciado no build. É o padrão para o target `:browser`. `node_modules` não passa pela compilação `:advanced`.
`:closure`:: Funciona de maneira parecida com o `:shadow` mas tenta processar todos os arquivos incluidos através do Closure Compiler CommonJS/ES6, facilidade de reescritas. Também são processado através da compilação `:advanced`.  

.`:shadow` vs `:closure`
****
Idealmente quermos usar `:closure` como nosso Provider de JS primário desde que ele vai rodar toda a aplicação através `:advanced` nos fornecendo o mais otimizado output. Contudo na prática a maioria dos códigos disponíveis via `npm` não é compátivel com as agressivas otimizações que a compilação `:advanced` faz. Eles também falham em compilar tudo ou expoem pequenos bugs em tempo de execução que são muito dificeis de identificar.

`:shadow` é uma ordenada solução paliativa que processa o código de maneira `:simple` e alcança um suporte confiável enquanto ainda consegue código razoavelmente otimizado. A saída é comparável (ou frequentemente melhor) a outras ferramentas como a gerada pelo `webpack` por exemplo.

Até suport em Closure ser mais confiável em `:shadow` é recomendado o JS provider para `:browser`.
****


.Exemplo de config parar usar `:closure` em um `:browser` build.
```clojure
{...
 :builds
 {:app
  {:target :browser
   ...
   :js-options {:js-provider :closure}
   }}}
```


=== Resolvendo pacotes [[js-resolve]]

Por padrão `shadow-cljs` vai resolver todos os requires `(:require ["thing" :as x])` seguinte a convensão `npm`. Isso significa que isso vai olhar o `<project>/node_modules/thing/package.json` e seguir o código de lá. Para customizar como isso funciona `shadow-cljs` expõe uma opção de configuração `:resolve` que permite você sobrescrever como as coisas são resolvidas.

==== Usando uma CDN [[js-resolve-global]]

Digamos que você já tenha React incluido na página via um CDN. Você deveria apenas começar usando `js/React` novamente mas nós paramos de fazer isso por uma boa razão. Ao invés disso você pode continuar a usar (:require ["react" :as react])` mas configura como resolve o "react"!

Aqui está um exemplo de config `shadow-cljs.edn` para tal construção:

```
{...
 :builds
 {:app
  {:target :browser
   ...
   :js-options
   {:resolve {"react" {:target :global
                       :global "React"}}}}

  :server
  {:target :node-script
   ...}}}
```

A build `app` vai agora usar uma instância do `React` global enquanto o `:server` build continua usando o pacote npm "react". Não há necessidade de violar o código pra fazer isso funcionar.

==== Redirecionando “require” [[js-resolve-npm]]

Algumas vezes você quer mais controle sobre quais pacotes `npm` estão na realidade dependendo da sua build. Você consegue "redirect" determinados requires do build config sem mudar o código. Isso é frequente útil se você não tem acesso ao fonte do qual seu pacote esta usando ou você apenas quer mudar ele para um build. 

```
{...
 :builds
 {:app
  {:target :browser
   ...
   :js-options
   {:resolve {"react" {:target :npm
                       :require "preact-compat"}}}
```

==== Limitações [[js-resolve-limitations]]

O `:shadow-js` e `:closure` tem total controle sobre `:resolve` e tudo mencionado acima funciona sem desvantagens. O `:js-provider :require` contudo, é mais limitado. Apenas o require inicial pode ser influênciado desde o padrão `require` está no controle depois disso. Isso significa que não é possível influênciar o que o pacote deve `require` internamente. É portanto não recomendado ser usado com targets que sua `require` diretamente (ex. `:node-script`).

.Redirecionando "react" para "preact"
```
{...
 :builds
 {:app
  {:target :node-script
   ...
   :js-options
   {:resolve {"react" {:target :npm
                       :require "preact-compat"}}}
```
.Exemplo use react-table
```
(ns my.app
  (:require
    ["react-table" :as rt]))
```

O exemplo acima funciona bem no navegador desde que cara `"react"` requerido seja substituido, incluindo o `"react"` requer `"react-table"` internamente. Para `:js-provider :require` contudo um `require("react-table")` será emitido e `node` esta controlando como isso é resolvido. Significando que isso será resolvido no padrão `"react"` e não o `"preact"` que tinhamos configurado.

=== Alternar diretório de módulos [[alt-node-modules]]

Por padrão `shadow-cljs` só olha para o `<project-dir>/node_modules` quando resolvendo pacotes JS. Isso pode ser configurado através da opção `:js-package-dirs` em `:js-options`. Isso pode ser aplicado globalmente ou por build.

Paths relativos serão resolvido para a raíz do projeto. Paths serão scaneados da esquerda para a direita e o primeiro pacote que combine será usado.

.Config global `shadow-cljs.edn`
```
{...
 :js-options {:js-package-dirs ["node_modules" "../node_modules"]}
 ...}
```

.Config aplicado para um único build

```
{...
 :builds
 {:app
  {...
   :js-options {:js-package-dirs ["node_modules" "../node_modules"]}}}}
```


== Lidando com arquivos .js [[classpath-js]]

****
*Atenção: Essa funcionalidade é um experimento!* É suportado atualmente em `shadow-cljs` e outras ferramentas CLJS podem gerar problemas se você tentar usar ela. Use isso colocando sua conta em risco. A funcionalidade foi inicialmente rejeitada a partir do CLJS core mas eu acredito ser útil e não deveria ter sido https://dev.clojure.org/jira/browse/CLJS-2061?focusedCommentId=46191&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-46191[anulada] sem um discussão mais longa.

CLJS tem uma alternada https://clojurescript.org/guides/javascript-modules[implementacão] que por sua vez não é suportada pelo `shadow-cljs`. Eu achei que essa implementação esta se perdendo em certos aspectos então eu optei por diferentes soluções. Feliz em discutir os prós/contra de ambas abordagens. 
****

Nós cobrimos como os pacotes <<npm, npm>> são usados mas você deve estar trabalhando no codebase que já tem um monte de Javascript puro e você não quer sobrescrever tudo em ClojureScript ainda. `shadow-cljs` 100% de interoperabilidade entre JavasScript e ClojureScript. O que significa que seu JS pode usar CLJS e o CLJS pode usar o JS.

Só é necessário apenas algumas convenções que você precisa seguir com a finalidade disso funcionar mas há chances de você já estar fazendo isso de qualquer maneira.

=== Requerindo JS

Já cobrimos como os pacotes `npm` são acessado através de seu nome mas no classpath acessamos os arquivos `.js` por ambos os caminhos, path absoluto ou relativo para o namespace atual.

.Carregando JS a partir do classpath
```clojure
(ns demo.app
  (:require
    ["/some-library/components/foo" :as foo]
    ["./bar" :as bar :refer (myComponent)]))
```

TIP: A extensão `.js` será adicionada automáticamente mas é possível especificar a extensão se você preferir. Perceba que atualmente apenas o `.js` é suportado.

Require absoluto como `/some-library/components/foo` significa que o compilador vai procurar por uma `some-library/components/foo.js` no classpath; ao contrário `node` que carregaria o arquivo a partir do filesystem. A mesma regra de classpath é aplicada para os arquivos no seu `:source-paths` ou em algumas biblioteca de terceiros `.jar` que você estiver usando.

Requires relativos são resolvidos primeiro procurando o namespace atual e então resolvendo um path relative a partir do nome. No exemplo acima estamos em `demo/app.cljs` para o requerimento `./bar` se resolver para  `demo/bar.js`, então isso é idêntico para `(:require ["/demo/bar"])`.

IMPORTANTE: O arquivo não deve ser fisicamente alocado no mesmo diretório. Ao invés disso a procurar pelo arquivo vem a tona no classpath. Isso é o contrário de node do qual espera sempre resolver a arquivos físicos.

.Exemplo de estrutura de arquivos com paths separados
```text
.
├── package.json
├── shadow-cljs.edn
└── src
    └── main
        └── demo
            └── app.cljs
    └── js
        └── demo
            └── bar.js
```

=== Language Support

IMPORTANTE: É experado que o classpath contenha apenas JavaScript que podessa ser consumido sem qualquer pre processamento feito pelo compilador. `npm` tem uma convenção muito similar.

O Closure Compiler é usado para processar todo o JavaScript encontrado no classpath usando a configuração de linguagem `ECMASCRIPT_NEXT`. E o que exatamente isso significa não é muito bem documentado mas é na maioria das vezes representa as próxima geração de código JavaScript da qual nem mesmo deve ser suportada pela maioria dos navegadores ainda. ES6 é muito suportado assim como a maioria das funcionalidades do ES7. Similarmente para o padrão CLJS isso será compilado para ES5 com polyfills quando necessário.

=== Dialetos JavaScript

Desde que existem muito dialetos populares em JavaScript (JSX, CoffeScript, etc) que não são diretamente analisaveis pelo Closure Compiler, precisamos pre-processar eles antes de colocar no classpath. https://babeljs.io/[babel] é comumente usado no mundo JavaScript então vamos usar `babel` para processar os arquivos `.jsx` como um exemplo aqui.

.Exemplo do config shadow-cljs.edn
```
{:source-paths
 ["src/main"
  "src/gen"]
 ...}
```

.Exemplo da estrutura de arquivos
```text
.
├── package.json
├── shadow-cljs.edn
└── src
    └── main
        └── demo
            └── app.cljs
    └── js
        ├── .babelrc
        └── demo
            └── bar.jsx
```

IMPORTANTE: Perceba como `src/js` não é adicionado para `:source-paths` o que significa que não vai estar no classpath.

.src/js/demo/bar.jsx
```jsx
import React from "react";

function myComponent() {
  return <h1>JSX!</h1>;
}

export { myComponent };
```

Rodamos https://babeljs.io/docs/usage/cli/[babel para converter os arquivos e escrever eles para ser configurado no diretório `src/gen`. Que é o diretório que você vai usar para você. Eu prefiro `src/gen` para os arquivos gerados.

```bash
$ babel src/js --out-dir src/gen
# or during development
$ babel src/js --out-dir src/gen --watch
```

`babel` é por si só configurado atrav;es do `src/js/.babelrc`. Veja o [exemplo oficial do JSX](https://babeljs.io/docs/plugins/transform-react-jsx/).

.JSX minimal .babelrc
```json
{
  "plugins": ["transform-react-jsx"]
}
```

Uma vez que `babel` escreve o `src/gen/demo/bar.js` será possível usar ele via ClosureScript e vai ser recarregado assim como o código ClojureScript.

IMORTANTE: `shadow-cljs` atualmente não provê suporte para rodar essa transformação. Por favor, use as ferramentas padrões (ex. `babel`, `coffescript`, etc.).

=== Acessando CLJS a partir do JS

As fontes JS podem ser acessadas por todo seus ClojureScript (e a Closure Library) diretamente importando seus namespaces com o prefixo `goog:` do qual o Compiler vai subrescrever o namespace como o padrão de exportação ES6.

```
import cljs, { keyword } from "goog:cljs.core";

// construct {:foo "hello world"} in JS
cljs.array_map(keyword("foo"), "hello world");
```

TIP: O prefixo `goog:` atualmente só funciona para os arquivos ES6. `require("goog:cljs.core")` não funciona.

== Migrando cljsjs.* [[cljsjs]]

> CLJSJS é um esforço para empacotar bibliotécas Javascript e ser capaz de usar elas com ClojureScript.

Desde que `shadow-cljs` consegue acessar <<npm, npm packages>> diretamente nós não precisamos contar com um reembalo dos pacotes https://github.com/cljsjs/packages[CLJSJS].

Contudo muitas bibliotecas CLJS ainda estão usando pacotes CLJSJS e eles quebrariam com `shadow-cljs` desde que isso não é mais suportado. Porém é bem simples de imitar esses namespaces `cljsjs` desde que eles são contruídos a partir dos pacotes `npm`. Isso deve requerer um arquivo que mapeia o `cljsjs.thing` para o pacote `npm` original e expõe a variavel globalmente.

Para React isso requer um arquivo como `src/cljsjs/react.cljs`:

```
(ns cljsjs.react
  (:require ["react" :as react]
            ["create-react-class" :as crc]))
```

```
(js/goog.object.set react "createClass" crc)
(js/goog.exportSymbol "React" react)
```

Desde que será tedioso para todo mundo fazer isso manualmente criei a biblioteca https://github.com/thheller/shadow-cljsjs[`shadow-cljsjs`] da qual provê apenas isso. Não inclui cada pacote mas irei continuar adicionando eles e contribuições são muito bem vindas também.

NOTE: A biblioteca `shadow-cljsjs` provê apenas arquivos de "calço". Ainda é necessário dar o `npm install` para os pacotes atuais de qualquer modo.

=== Por que nnao usar CLJSJS?

Pacotes CLJS basicamente pegam um pacote do `npm` e coloca ele dentro de um `.jar` e re-publica eles através do https://clojars.org[clojars]. Como um bônus eles frequentemente empacota pacotes externos. O compilador de outro modo não faz nada com esses arquivos e apenas prefixa eles para o output gerado.

Isso foi bastante útil no passado quando nós não tinhamos acesso ao `npm` diretamente mas tem certos problemas desde que nem todos os pacotes são facilmente combinados com outros. Um pacote que deve contar com `react` mas ao invés de expressar isso via `npm` https://github.com/cljsjs/packages/tree/master/material-ui[eles]fazem o bundle do próprio `react`. Se você não tomar cuidado você poderia incluir duas versões diferentes de `react` no seu build do qual levaria a erros confusos ou pelo menos aumentar o tamanho do build substancialmente.

Além disso não todo pacote `npm` é disponível via CLJSJS e manter as versões dos pacotes sincronizadas requer trabalho manual, do qual significa que os pacotes estão frequentemente desatualizados.

`shadow-cljs` não suporta CLJSJS para evitar conflito no seu código. Uma biblioteca deve tentar usar a versão "antiga" do `cljsjs.react` enquando outra usa a nova `(:require ["react"])` diretamente. Isso iria novamente levar a duas versões de `react` na sua página novamente.

Então a única coisa que estamos esquecendo são os blundles externos. Em muitos exemplos eles não é requerido que seja melhorado <<infer-externs, externs inference>>. Frequentemente esses externos são gerados usando uma ferramenta de terceiros do qual significa que eles não são totalmente precisos de qualquer modo.

Conclusão: Use <<npm, npm>> diretamente. Use <<infer-externs, :infer-externs auto>>.
