O modo de desenvolvimento sempre tem saídas individuais para cada namespace, assim eles conseguem ser recarregados de maneira isolada.
Quando você estiver pronto pra fazer o deploy do código para um servidor você quer rodar o Closure Compiler
para gerar um único resultado minificado para cada <<Modules, module>>.

Por padrão os arquivos de saída do modo release deve ser apenas visto em substituição para os arquivos do
modo de desenvolvimento: não existe diferenças na maneira de incluir eles no HTML. Você deve usar 
<<NameHashing, filename hashing>> para melhorar as caracteristicas de chaching no navegador.

.Gerando Saída Minificada
```
$ shadow-cljs release build-id
```

== Configuração de Release

Geralmente você não vai precisar adicionar nenhuma configuração extra pra criar uma versão de release para seu build. A configuração padrão já captura tudo que é necessário e deveria apenas requerer configuração extra se você quer sobrescrever o padrão.

Cada `:target` já provê bons padrões otimizados para cada plataforma então você vai ter menos com o que se preocupar.

=== Otimizações [[Otimizações]]

Você pode escolher o nível de otimização usando a seção `:compiler-options` da configuração:

IMPORTANTE: Geralmente você não precisa configurar `:optimizations` desde que o `:target` já esteja no nível apropriado.

IMPORTANTE: `:optimizations` apenas aplicam quando usando o comando `release`. Builds de desenvolimento nunca são otimizadas pelo Closure Compiler. Elas são sempre configuradas para `:none`.

```clojure
{...
 :build
   {:build-id
     {...
      :compiler-options {:optimizations :simple}}}}
```

Veja o https://developers.google.com/closure/compiler/docs/compilation_levels[the Closure compiler's documentation]
para mais informações sobre os níveis de otimização disponíveis.

=== Release-Specifico vs. Configuração de desenvolvimento

Se você deseja ter valores de configurações separadas em um build quando rodando um build de release então você
pode sobrescrever as configurações incluindo um `:dev` e/ou seção `:release` no build:

.Exemplo do `shadow-cljs.edn` build config
```clojure
{:source-paths ["src"]
 :dependencies []
 :builds
 {:app
  {:target :browser
   :output-dir "public/js"
   :asset-path "/js"
   :modules {:base {:entries [my.app.core]}}

   ;; Here is some dev-specific config
   :dev {:compiler-options {:devcards true}}

   ;; Here is some production config
   :release {:compiler-options {:optimizations :simple}}}}}
```

== Externs [[externs]]

Desde que nós queremos que os builds sejam completamente otimizados pelo Closure Compiler precisamos lidar a compilação `:advanced` https://developers.google.com/closure/compiler/docs/api-tutorial3[Externs]. Externos representa pedaços de códigos que não são incluídos qaundo fazendo compilação `:advanced` . `:advanced` trabalha fazendo otimizações de todo oprograma mas existe algum código que não seja capaz de incluir, então externs informa ao Compiler sobre esse código. Sem o externs o Compiler deve renomear ou remover algum código que não deveria.

Tipicamente todas as dependências JS são estrangeiras e não serão passadas através do `:advanced` e assim requer Externs.

DICA: Externs são requeridos apenas para `:advanced`, ele não são requeridos no modo `:simple`.

=== Inferência Externa [[infer-externs]]

Para ajudar a lidar com Externs o compilidador `shadow-cljs` provê uma inferência externa melhorada que pode ser habilitada configurando `:infer-externs :auto` para seu build.

.Exemplo do Config
```clojure
{...
 :builds
 {:app
  {:target :browser
   ...
   :compiler-options {:infer-externs :auto}
   }}}}
```

Com `:auto` o compilador vai executar "checks" adicionais em tempo de compilação, apenas para seus arquivos. Isso não vai alertar você sobre possíveis problemas externos no código das bibliotecas. `:all` vai habilitar para qualquer coisa mas esteja consciênte que você vai receber uma grande quantidade de alertas.

Quando habilitade você vai vai receber alguns alertas sempre que o Compilador não descobrir se você esta trabalhando com código JS ou CLJS.

.Exemplo de código
```
(defn wrap-baz [x]
  (.baz x))
```

.Exemplo de alerta
```text
------ WARNING #1 --------------------------------------------------------------
 File: ~/project/src/demo/thing.cljs:23:3
--------------------------------------------------------------------------------
  21 |
  22 | (defn wrap-baz [x]
  23 |   (.baz x))
---------^----------------------------------------------------------------------
 Cannot infer target type in expression (. x baz)
--------------------------------------------------------------------------------
```

Na opção `:advanced` o compilador vai ser renomado `.baz` para algo mais "curto" e o Externs informa ao compilador que isso é uma propriedade externa que não deverá ser renomado.

`shadow-cljs` pode gerar o externs apropriado se você adicionar o typehint para o objeto que você está executando a interoperabilidade nativa.

.Type-hint par ajudar na geração de externs 
```clojure
(defn wrap-baz [x]
  (.baz ^js x))
```

O `^js` vai dizer ao compiler para gerar o extern adequado e o vai desaparecer. A propriedade agora está segura quando a renomear. 

.Multiplas chamadas de interoperabilidade
```clojure
(defn wrap-baz [x]
  (.foo ^js x)
  (.baz ^js x))
```

Pode ser tedioso declarar para cada chamada de interoperabilidade, então é possível declarar o bind da variabel. Isso será usando em todo o escopo pra essa variavel. Externs para ambas as chamadas ainda serão gerados.

.Declare `x` diretamente
```clojure
(defn wrap-baz [^js x]
  (.foo x)
  (.baz x))
```

IMPORTANT: Não declare tudo com `^js`. Algumas vezes você deve estar fazendo interop no CLJS ou nos objetos ClosureJS. Eles não requerem externs. Se você tiver certeza que está trabalhando com objetos CLJS é melhor usar o `^clj` hint.
Não se preocupe se você usar `^js` incorretamente mas ele deve afetar algumas otimizações quando uma variavel não for renomeada quando deveria ser.

Chamadas globais não requrem o typehint quando usando diretamente `js/`.

.No hint requerido, inferência externa é automátic
```
(js/Some.Thing.coolFunction)
```

Chamada no `:require` bindings são também inferidas automáticamente.

.Nenhum hint é requerido para `:as` e `:refer`
```
(ns my.app
  (:require ["react" :as react :refer (createElement)]))

(react/createElement "div" nil "hello world")
(createElement "div" nil "hello world")
```

=== Externs Manual

Algumas bibliotecas provê externs como um arquivo `.js` separado. Você pode incluir eles dentro do seu build através da opção de compilação `:externs`.

.Manual Externs Config
```
{...
 :builds
 {:app
  {:target :browser
   ...
   :compiler-options {:externs ["path/to/externs.js" ...]}
   }}}
```

DICA: O compiler procurar por arquivos relativos ao projeto raiz primeiro. Isso vai também mirar pra carregar eles a partir do classpath se nenhum arquivo for encontrado.

=== Externs Simplificado

Escrevendo externs na mão pode ser desafiador e `shadow-cljs` provê uma maneira de escrever uma maneira mais coveniente para escrever eles. Com `shadow-cljs check <your-build>` você pode rapidamente adicionar os externs missing.

Comece criando um `externs/<your-buid>.txt`, então build `:app` seria `externs/app.txt`. Nesse arquivo cada lina deveria ser uma palavra especificando uma propriedade JS que não deveria ser renomeado. Variaveis globais deveriam ser prefixadas pelo `global:`

.Exemplo externs/app.txt
```
# this is a comment
foo
bar
global:SomeGlobalVariable
```

Nesse exemplo o compilador vai parar de renomar o `something.foo()`, `something.bar()`.

== Code Stripping

O Closure Compiler suporta remover código por nome. Isso permite remover código que o processor normal de dead-code não consegue remover. Isso é um pouco perigoso porque pode remover código que você na verdade se preocupa mas isso pode remover um monte de dev code facilmente. Isso é agrupado em 4 opções separadas das quais praticamente apenas a `:strip-type-prefixes` são relevantes para o ClojureScript mas os outros devem ser úteis também.

.Exemplo removendo todos os usos de `cljs.pprint`
```
{...
 :builds
 {:app
  {:target :browser
   ...
   :compiler-options {:strip-type-prefixes #{"cljs.pprint"}
   }}}
```

Cada uma dessas opções são especificadas como um conjunto de Strings. Por favor, perceba que todos os nomes especificados aqui são nomes JS então certamente CLJS devem ser usados. `my-lib.core` se torna `my_lib.core`

[Horizontal]
`:strip-types`:: Permite remover declarações deftype/defrecord. `#{"my.ns.FooBar"}` remove `(defrecord FooBar [])`.
`:strip-type-prefixes`:: Remove tudo começando com um determinado Prefixo. Permite remover namespaces CLJS completos.
`:strip-name-prefixes`:: Permite remover propriedades por prefixo. `#{"log"}` remove `this.logX` ou `(defn log-me [...])`
`:strip-name-suffixes`:: Permite remover propriedades por sufixo. `#{"log"}` remove `this.myLog` ou `(defn my-log [...])`

****
*DANGER: Seja cuidado com essas opções. Elas são aplicadas ao seu build como um todo e deve remover código que na verdade é necessário. Você deve acidentalmente remover código em bibliotecas não escritas por você. Sempre conside outras opções antes de usar esse.*
****

== Build Report

`shadow-cljs` consegue gerar um relatório detalhado para o build de `release` dos quais inclui uma repartição detalhada dos fontes incluidos e quanto cada um deles contribue para o tamanho do build no geral.

Um relatório simples pode ser encontrado https://code.thheller.com/demos/build-report/huge.html[aqui].

```bash
$ npx shadow-cljs run shadow.cljs.build-report <build-id> <path/to/output.html>
# example
$ npx shadow-cljs run shadow.cljs.build-report app report.html
```

O exemplo acima vai gerar um `report.html` no diretório do seu projeto para o build `:app`.

DICA: O `report.html` gerado é inteiramente independente e inclue todos os requeridos data/js/css. Nenhuma outra fonta externa é requerida.
