= REPL

O REPL é uma ferramenta muito poderosa para se ter quando trabalhando com Clojure(Script). `shadow-cljs` provê diversas variantes integradas que permite você iniciar rapidamente assim como as variantes que são integradas no seu build padrão.

Quando você rapidamente quer testar algum código externo o built-in REPLS deveria ser o suficiente. Se você precisa de uma configuração mais complexa que também faz coisas por si só é mais recomendado usar o build atual.

== ClojureScript REPL

Por padrão você pode escolher entre um `node-repl` e um `browser-repl`. Ambos trabalham similarmente e o fator diferenciado é que o um roda em um processo node controlado enquanto o outro abre o Browser Windows que vai ser usado para avaliar o código atual.

=== Node REPL [[node-repl]]

```bash
$ shadow-cljs node-repl
```

Isso inicia um REPL CLJS em branco com um processo `node` já conectado.

IMPORTANTE: Se você sair do REPL Node o processo `node` também vai ser fechado.

`node-repl` permite você iniciar sem uma configuração adicional. Ele tem acesso a todo seu código pelos meios usuais, ex. `(require '[your.code :as x])`. Desde que isso não está conectado a nenhum build ele não faz nenhum rebuilding automático do código quando seus arquivos mudarem e não provê um hot-reload.

=== Browser REPL [[browser-repl]]

```bash
$ shadow-cljs browser-repl
```

Isso inicia um REPL CLJS e vai abrir um Browser Window associoado onde o código vai ser executado. Além de rodar no Browser isso tem tudo a mesma funcionalidade como o `node-repl` acima.

IMPORTANTE: Se você fecha o Browser Window o REPL vai parar de funcionar.

=== Build-specific REPL [[build-repl]]

`node-repl` e `browser-repl` funciona sem nenhuma configuração especifica de build. Isso significa que eles vão apenas fazer o que você falar pra fazer mas nada por eles próprio.

Se você quer buildar uma coisa em especifico você deveria configurar um build usando um dos build-targets providos. A maioria deles automaticamente injeta o código necessário para o REPL ClojureScript. Isso não deveria requerer nenhuma configuração adicional. Para o build CLJS REPL funcionar você precisa de 2 coisas

. um `watch` para seu build
. conectar a runtime JS do `:target`. Significando que se você está usando o target `:browser` você precisa abrir um Browser que tem o JS gerado carregado. Para  builds node.js que significa rodar o processo `node`.

Uma vez você tem ambos conectado você ao REPL CLJS via linha de comando ou a partir de um Clojure REPL.

.CLI
```bash
$ shadow-cljs watch build-id
...

# different terminal
$ shadow-cljs cljs-repl build-id
shadow-cljs - connected to server
[3:1]~cljs.user=>
```

.REPL
```bash
$ shadow-cljs clj-repl
...
[2:0]~shadow.user=> (shadow/watch :browser)
[:browser] Configuring build.
[:browser] Compiling ...
[:browser] Build completed. (341 files, 1 compiled, 0 warnings, 3,19s)
:watching
[2:0]~shadow.user=> (shadow/repl :browser)
[2:1]~cljs.user=>
```

DICA: Digite `:repl/quit` para sair da REPL. Isso vai apenas sair do REPL, o `watch` vai permanecer rodando.

TIP: Você deve rodar multiplos `watch` "workers" em paralelo e conectar/disconectar to seus REPLs a qualquer momento.

.Erro nenhum runtime conectada.
``` text
[3:1]~cljs.user=> (js/alert "foo")
There is no connected JS runtime.
```

Se você ver isso você precisa abrir seu App no Browser ou começar um processo `node`.

== Clojure REPL

Um REPL Clojure é também provido além do ClojureScript REPLs providos. Isso pode ser usado para controlar o processo `shadow-cljs` e rodar todos os outros comandos build através disso. Você pode começar com um Clojure REPL e então atualizar isso para um CLJS REPL em qualquer ponto (e voltar).

.Rodando a partir de um CLI
```bash
$ shadow-cljs clj-repl
...
shadow-cljs - REPL - see (help), :repl/quit to exit
[1:0]~shadow.user=>
```

O namespace `shadow.cljs.devtools.api` tem funções que mapeia maios ou menos 1:1 para o CLI. São apelidado como `shadow` por padrão.

.Exemplo dos commandos
```clojure
;; shadow-cljs watch foo
(shadow.cljs.devtools.api/watch :foo)
;; this is identical, due to the provided ns alias
(shadow/watch :foo)
;; shadow-cljs watch foo --verbose
(shadow/watch :foo {:verbose true})
;; shadow-cljs compile foo
(shadow/compile :foo)
;; shadow-cljs release foo
(shadow/release :foo)

;; shadow-cljs browser-repl
(shadow/browser-repl)
;; shadow-cljs node-repl
(shadow/node-repl)
;; shadow-cljs cljs-repl foo
(shadow/repl :foo)

;; Once you are in a CLJS REPL you can use
:repl/quit
;; or
:cljs/quit
;; to drop back down to CLJ.
```


=== Embedded [[embedded]]

Também é possível usar o `shadow-cljs` inteiramente de dentro de qualquer outro processo CLJ. Enquanto o artefato `thheller/shadow-cljs` foi carregado no classpath você está pronto pra seguir.

.Exemplo usando `lein repl`
```bash
$ lein repl
nREPL server started on port 57098 on host 127.0.0.1 - nrepl://127.0.0.1:57098
REPL-y 0.4.3, nREPL 0.6.0
Clojure 1.10.0
...

user=> (require '[shadow.cljs.devtools.server :as server])
nil
user=> (server/start!)
...
:shadow.cljs.devtools.server/started
user=> (require '[shadow.cljs.devtools.api :as shadow])
nil
user=> (shadow/compile :foo)
...
```

Você pode parar o servidor embedado rodando `(shadow.cljs.devtools.server/stop!)`. Isso também vai parar todos os processos de build rodando.

IMPORTANTE: Se você quer mudar para o REPL CLJS isso deve requerer configuração adicional na ferramenta que você usou para começar o servidor. Desde que `lein` vai por padrão requerer configuração adicional nREPL `:middleware`. Quando usando `clj` você está pronto para ir desde que ele não use o nREPL.
