O `:target :node-library` emite o código que pode ser usado (via `require`) como uma biblioteca node padrão, e é
útil para publicar seu código para re uso como um artefato Javascript compilado.

Como com outro modos o <<config, main configuration options>> é aplicado e deve ser configurado.
As opções target-specific são:

[horizontal]
`:target`:: Usa :node-library
`:output-to`:: (required). O caminho e o nome do arquivo para a biblioteca gerada.
`:output-dir`:: (optional). O caminho para os arquivos em modo de desenvolvimento. Padrão para o diretório de cache.

O hot code reload é siilar ao <<NodeHotCodeReload, the script target>>, mas não deve funcionar bem 
desde que isso não pode ser facilmente controlar tudo do código que é carregado.

Controlar o que o código na verdade exporta é feito através das seguintes opções:

- `:exports` - um mapa de keyword para simbolos totalmente qualificados
- `:exports-var` - um simbolo totalmente qualificado
- `:exports-fn` - um simbolo totalmente qualificado

=== Single static "default" export

`:exports-var` irá apenas retornar o que for declarado sob essa var. Isso pode apontar para um `defn` ou o `def`.

.Construindo o config usando `:exports-var`
```
{...
 :builds {:lib {:output-to "lib.js"
                :exports-var demo.ns/f
                ...}}}
```
.Exemplo CLJS
```
(ns demo.ns)

(defn f [...] ...)
;; OR
(def f #js {:foo ...})
```

.Consumindo o código gerado
```bash
$ node
> var f = require('./lib.js');
f(); // the actual demo.ns/f function
```

Isso está gerando efetivamente o `module.exports = demo.ns.f;`

=== Multiplos exports nomeados estáticos

.Build configuration com multiples exports
```
{...
 :builds {:lib {:exports {:g       demo.ns/f
                          :h       other.ns/thing
                          :ns/ok?  another.ns/ok?}
                ...}}}
```

A keyword é usada como o nome da entidade em um objeto exportado. *Nenhum assalto é feito* para essa keyword
(mas os namespaces são soltos). Então, o exemplo abaixo de mapas cljs `f` para `g`, etc.:

```bash
$ node
> var lib = require('./lib.js');
lib.g(); // call demo-ns/f
lib["ok?"](); // call another-ns/ok?
```

É possível alcançar o mesmo resultado usando `:exports-var` apontando para o `def`

```
(def exports #js {:g f
                  ...})
```

=== Exportes "Dinâmicos"

Além do que você deve especificar o `:exports-fn` como um simbolo completamente qualificado. Isso deveria apontar para uma função sem argumentos dos quais deveria retornar um objeto JS (ou função). Essa função vai apenas ser chamada uma vez como `node` e cachear o valor retornado. 

```clojure
(ns demo.ns
  (:require [demo.other :as other]))

(defn generate-exports []
  #js {:hello hello
       :foo other/foo})
```


```clojure
{...
 :builds {:lib {:exports-fn demo.ns/generate-exports
                ...}}}
```

ATENÇÃO: Os exports de config automaticamente rastreia os simbolos exportados e passa eles para um estágio de otimizações. Isso significa que tudo listado em `:exports` não vai ser renomeado pelas otimizações do Google Closure.

=== Exemplo Completo

O exemplo abaixo cria um arquivo `lib.js` para ser consumido via o mecanismo Node `require`.

```
(ns demo.lib)

(defn hello []
  (prn "hello")
  "hello")
```

O build configuration deveria ser:

```
{...
 :builds {:library {:target    :node-library
                    :output-to "out/demo-library/lib.js"
                    :exports   {:hello demo.lib/hello}}}}
```


E o uso do runtime funcionaria como o esperado:

```
$ cd out/demo-library
$ node
> var x = require('./lib');
undefined
> x.hello()
hello
'hello'
```

Como `:node-script` isso apenas criaria o arquivo especificado em `:output-to`. O mapa `:exports` mapeia as variaveis CLJS para o nome eles deveriam ser exportados para.

ATENÇÃO: O modo de desenvolvimento tem o <<NodeModes,same setup>> como para scripts node (dependencias extra).
