Quando você quiser rodar seus tests CLJS no browser ou em algum tipo de servidor de CI você vai precisar
ser capaz de rodar os testes a partir da linha de comando e receber um status code como resposta. Karma é um bem conhecido
e suportado test runner que consegue fazer isso para você, e `shadow-cljs` inclu o target que
pode adicionar os wrappers apropriados nos seus testes para que funcione adequadamente.

=== Instalando Karma

See their http://karma-runner.github.io[website] for full instructions. You'll typically need
something like this is your `package.json`:

```json
{
  "name": "CITests",
  "version": "1.0.0",
  "description": "Testing",
  ...
  "devDependencies": {
    "karma": "^2.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cljs-test": "^0.1.0",
    ...
  },
  "author": "",
  "license": "MIT"
}
```

Então, você precisa do Karma, um browser launcher, e a integração cljs-test.

=== O Build

The build options are:

[horizontal]
`:target`::     `:karma`
`:output-to`::  A path/filename for the js file.
`:ns-regexp`::  (optional) A regex to match the test namespaces, defaults to "-test$

Então você dever ter algo como esse:

```
{...
 :builds
 {:ci
  {:target :karma
   :output-to  "target/ci.js"
   :ns-regexp  "-spec$"}}}
```

Você também precisa de um `karma.conf.js`:

```javascript
module.exports = function (config) {
    config.set({
        browsers: ['ChromeHeadless'],
        // The directory where the output file lives
        basePath: 'target',
        // The file itself
        files: ['ci.js'],
        frameworks: ['cljs-test'],
        plugins: ['karma-cljs-test', 'karma-chrome-launcher'],
        colors: true,
        logLevel: config.LOG_INFO,
        client: {
            args: ["shadow.test.karma.init"],
            singleRun: true
        }
    })
};
```

então você pode rodar os testes do seguinte modo (assumindo que você tenha instalado globalmente as ferramentas):

```bash
$ shadow-cljs compile ci
$ karma start --single-run
12 01 2018 01:19:24.222:INFO [karma]: Karma v2.0.0 server started at http://0.0.0.0:9876/
12 01 2018 01:19:24.224:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
12 01 2018 01:19:24.231:INFO [launcher]: Starting browser ChromeHeadless
12 01 2018 01:19:24.478:INFO [HeadlessChrome 0.0.0 (Mac OS X 10.12.6)]: Connected on socket TcfrjxVKmx7xN6enAAAA with id 85554456
LOG: 'Testing boo.sample-spec'
HeadlessChrome 0.0.0 (Mac OS X 10.12.6): Executed 1 of 1 SUCCESS (0.007 secs / 0.002 secs)
```

