Esse é um target adicional que é pretendido que integre CLJS em um projeto JS existente. A saída pode perfeitamente integrar com ferramentas JS existentes (ex.: webpack, browserify, babel,
create-react-app, ...) com poucas configurações.

[horizontal]
`:output-dir`:: O caminho para a saída do arquivo, padrão é `node_modules/shadow-cljs`.
`:entries`:: (obrigatório) Um vetor de namespaces que devem ser compilados

.Exemplo do config `shadow-cljs.edn`
```
{...
 :builds
 {:code
  {:target :npm-module
   :entries [demo.foo]}}}
```

Se você usa o `:output-dir` padrão do `"node_modules/shadow-cljs"` você pode acessar o namescape declarado usando `require("shadow-cljs/demo.foo")` em JS. Quando não usando algo dentro do `node_modules` você deve incluir eles usando um path relativo. Com `:output-dir "out"` que deveria ser `require("./out/demo.foo")` a partir de seu projeto raíz.

Se você planeja distribuir o código no NPM, então você deve querer usar a <<NodeLibrary, `:node-library` target>> em vez idsso ele permite para um um melhor nível de controler sobre exports e otimizações.

== Trabalhando com otimizações

Ao contrário do target `:node-library`, o modulo target não conhece o que você quer chamar para os
simbolos que você está exportando, então isso apenas exporta eles as-is. Se vocie usar compilação avançanda, então tudo
vai ser minificado!

Essa é fácil de solucinar, simplesmentes adicione o metadado `:export` em qualquer simbolo que você quer preservar:

```
(ns demo.foo)

(def ^:export foo 5.662)

(defn ^:export bar [] ...)
```

Esse é a notação padrão que é entendida pelo ClojureScript e previne o Google Closure de 
renomear os artefatos. O código JS vai ainda ser capaz de acessar eles depois das otimizações. Sem a dica do `^:export` o closure-compile provavelmente vai ter removido ou renomeado eles.

```
var ns = require("shadow-cljs/demo.foo");

ns.foo;
ns.bar();
```

