O `:target :react-native` produz código que integra nas ferramentas padrões do `react-native` (ex. `metro`). Ferramentas como `expo` da qual encapsula essas ferramentas deveria automáticamente trabalhar e não requerer configuração adicional. 

Você vai precisar da configuração básica <<config,main configuration>> como em outro targets (como `:soure-paths`), o config do build especifico é minimo e requer pelo menos duas opções (alés da `:target`)

[horizontal]
`:init-fn`:: (obrigatório). A função inicial do seu app. Essa função será chamada uma vez na inicialização e provavelmente deveria renderizar alguma.
`:output-dir`:: (obrigatório). O diretório usado para escrever arquivos de saída.

// TODO: Thomas mentioned that node can be picky and sometimes output-dir is useful...an example would be nice.

.Exemplo da configuração do :react-native
```
{:source-paths [...]
 :dependencies [...]
 ...
 :builds
 {:app
  {:target :react-native
   :init-fn demo.app/init
   :output-dir "app"}}}
```

Quando compilando esse resultado em um arquivo `app/index.js` para ser usado como ponto de entrada para as ferramentas do `react-native`. Durante o desenvolvimento o `:output-dir` vai conter muito mais arquivos mas você deveria apenas referenciar o `app/index.js` gerado. Um build `release` vai apenas gerar o `app/index.js` otimizado e não requer arquivos adicionais.

== React Native

Existe duas maneiras de usar `react-native`, "plain" `react-native`, do qual permite você usar código nátivo e bibliotecas e um "wrapped" no https://expo.io/[expo] (descrito abaixo). Todos os passos descritos acima são suficientes para começar usando shadow-cljs como `react-native` puro. Veja esse exemplo de repo:

- https://github.com/thheller/reagent-react-native

== Expo

https://expo.io/[expo] funcionando com `react-native` de maneira fácil. Existem dois exemplos de configuração.

- https://github.com/thheller/fulcro-expo
- https://github.com/thheller/reagent-expo

Ambos exemplos onde gerados usando `expo init...` e apenas mudanças ajustadas no config estava adicionando o `entryPoint` adequado para o `app.json` gerado.

```
{
  "expo": {
    "name": "hello-world",
    "slug": "reagent-expo",
    ...
    "entryPoint":"./app/index.js",
    ...
  }
}
```

`expo` requer que o Component React seja registrado na inicialização da qual pode ser feita manualmente ou usando a função `shadow.expo/render-root` da qual cuida de criar o Component e diretamente expera uma instância de um element React para começar a renderizar.

.A partir do Reagent https://github.com/thheller/reagent-expo/blob/2c73ed0513a8f5050b250c0c7e53b9ae7543cee9/src/main/test/app.cljs#L34-L40[example]
```
(defn start
  {:dev/after-load true}
  []
  (expo/render-root (r/as-element [root])))

(defn init []
  (start))
```

`init` é chamado uma vez na inicialização. Desde o exemplo nnao precisa fazer nenhuma configuração especial isso apenas chama o `start` diretamente. `start` vai ser chamado repetidamente quando `watch` está rodando cada vez depois de uma mudança. A função `reagent.core/as-element` pode ser usada para gerar o Elemento React requerido a partir de uma marcação do hiccup.
