Esse target destina-se a reunir namespaces que contém testes (pattern mach basedo no nome do arquivo),
e dispara um test runner. Contém um runner built-in que vai scanear automáticamente para testes `cljs.test`
e rodar eles.

As opções relevantes de configuração são:

[horizontal]
`:target`::    `:browser-test`
`:test-dir`::  A folder in which to output files. See below.
`:ns-regexp`:: (optional) A regular expression matching namespaces against project files. This only scans files, and
will not scan jars. Defaults to "-test$".
`:runner-ns`:: (optional) A namespace that can contain a start, stop, and init function. Defaults to
`shadow.test.browser`.

As opções normais de `:devtools` são suportadas, então você vai geralmente criar um servidor http para fornecer esses arquivos.
Em geral você vai precisar de um config parecido com esse:

```
{...
 :builds {:test     {:target    :browser-test
                     :test-dir  "resources/public/js/test"
                     :ns-regexp "-spec$"
                     :runner-ns tests.client-test-main
                     :devtools  {:http-port          8021
                                 :http-root          "resources/public/js/test"}}
```

Relembre que o diretório de testes tem que ter um index.html, e uma pasta js.

Se você escolher fornecer um `:runner-ns` costumizado, ele deve parecer algo como esse:

```
(ns tests.client-test-main)

(defn start []
  ... run the tests...)

(defn stop [done]
  ; tests can be async. You must call done so that the runner knows you actually finished
  (done))

(defn ^:export init []
  (start))
```

Ele apenas tem os métodos `init`, `start`, `stop`. `init` vai ser chamado uma vez no startup, `stop` vai ser chamado antes de qualquer que for código recarregado e o `start` será chamado depois que todo o código for recarregado.

DICA: `:runner-ns` é opcional, apenas deixe ele de fora para usar o padrão.

=== Saída gerada no `:test-dir`

A saída inclue dois artefados primarios em sua pasta `test-dir`:

* `index.html` - Se e apenas se não existia um arquivo `index.html`. Por padrão o arquivo gerado carrega os testes e roda o `init` no `:runner-ns`. Você deve editar ou adicionar versões customizadas que não iram ser sobrescritas.
* `js/test.js` - Os testes Javascript. Os testes sempre vão ter esse nome. As entradas para o modulo são auto-geradas.
