
= Uso

`shadow-cljs` pode ser usando de diversas maneiras mas em geral o fluxo de trabalho permanece o mesmo.

Durante o desenvolvimento você tem a opção de `compilar` uma build uma vez ou rodar um worker `watch` do qual vai assistir a mudanças nos seus arquivos fontes e re-compilar eles automaticamente. Quando o <<devtools, enabled>> `watch` também recarrega seu código e provê uma REPL. Durante o desenvolvimento o foco é na experiência do desenvolvedor com rápidos ciclos de feedback. O código de desenvolvimento nunca deveria ser publicado em produção.

Quando chegar o momento de criar uma build de <<release, `release`>> da qual cria um build otmizado adequado para produção. Para isso o https://developers.google.com/closure/compiler/[Closure Compiler] é usado porque aplicar algumas otimizações `:advanced` para seu código criar o a melhor saída possível. Isso deve requerer alguns <<externs, tuning>> para que funcione adequadamente quando usando um monte de interop com JavaScript nativo mas funciona perfeitamente para ClojureScript (e o código a partir da https://developers.google.com/closure/library/[Closure Library]).

== Linha de comando

Se <<Installation, installed>> globalmente, você consegue usar o comando `shadow-cljs` diretamente.

```bash
$ shadow-cljs help
```

Se você preferir usar apenas o `npm` local você consegue invocar ele via `npx` ou `yarn`.

```bash
# npm
$ npx shadow-cljs help

# yarn
$ yarn shadow-cljs help

# manually
$ ./node_modules/.bin/shadow-cljs help
```

.Comandos `shadow-cljs` comumente usados durante o desenvolvimento
```bash
# compile a build once and exit
$ shadow-cljs compile app

# compile and watch
$ shadow-cljs watch app

# connect to REPL for the build (available while watch is running)
$ shadow-cljs cljs-repl app

# connect to standalone node repl
$ shadow-cljs node-repl
```

.Rodando um build de release otimizado para usar em produção.
```
$ shadow-cljs release app
```

Alguma vezes você deve encontrar alguns problemas relacionados a compilação `:advanced`. Esses
comandos podem ajudar a rastrear as causas.

.Comando release debugging.
```
$ shadow-cljs check app
$ shadow-cljs release app --debug
```

=== Server Mode [[server-mode]]

Um comando `shadow-cljs` pode ser bastante lento pra iniciar. Para melhorar isso o `shadow-cljs` pode rodar em "server mode" o que significa que um processo dedicado é iniciado do qual todos os outros comando podem usar para executar um pouco mais rápido desde que eles não precisam iniciar uma nova instância JVM/Clojure.

Comando que fazendo coisas demoradas implicitamente iniciam uma instância do servidor (ex. `watch`) mas isso é frequentemente aconselhavel ter
um processo dedicado no servidor rodando.

Você pode rodar o processo em primeiro plano no terminal dedicado. Use o `CTRL+C` para terminar o servidor.

```bash
$ shadow-cljs server

# or (if you'd like REPL to control the server process)
$ shadow-cljs clj-repl
```

É possível rodar o servidor em segundo plano através das funções `start|stop|restart`.

```bash
$ shadow-cljs start
$ shadow-cljs stop
$ shadow-cljs restart
```

Uma vez que qualquer servidor rodando cada outro comando vai usar isso e rodar mais rápido.

== Build Tool Integration

`shadow-cljs` consegue integrar com outras ferramentas Clojure desde a primeira distribuição é apenas um arquivo `.jar` disponível através do https://clojars.org/thheller/shadow-cljs[Clojars]. Por padrão seu `:dependencies` são gerenciados via as versões `shadow-cljs`. Mas você consegue usar outras builds tools para gerenciar suas dependencias também.

CUIDADE: É fortemente recomendado usar as versões padrões do `shadow-cljs`. O comando faz um monte de coisas para otimizar a experiência do usuário (ex: inicialização mais rápida) das quais não são feitas em outras ferramentas. Você vai evitar um monte de dor de cabeça lidando com conflito de dependências e outros erros relacionados.

=== Leiningen [[Leiningen]]

Se você gostaria de usar  https://leiningen.org/[Leiningen] para gerenciar suas dependencias, você pode fazer isso adicionando um `:lein` em seu config `shadow-cljs.edn`. Com essa configuração, o comando `shadow-cljs` vai usar `lein` para subir a JVM, ignorando qualquer `:source-paths` e `:dependencies` em `shadow-cljs.edn`; confiando no `lein` para configurar eles a partir do `projct.clj`.

```
{:lein true
 ; :source-paths and :dependencies are now ignored in this file
 ; configure them via project.clj
 :builds { ... }
```

.Usando um `lein` profile dedicado
```
{:lein {:profile "+cljs"}
 :builds {...}}
```
.Sample project.clj
```
(defproject my-awesome-project
  ...
  :profiles
  {:cljs
   {:source-paths ["src/cljs"]
    :dependencies [[thheller/shadow-cljs "..."]
                   [reagent "0.8.1"]]}})
```

Quando usando `project.clj` para gerenciar suar `:dependencies` você deve manualmente incluir o artefato https://clojars.org/thheller/shadow-cljs[thheller/shadow-cljs] em seu `:dependencies` (diretamente ou em um profile).

IMPORTANTE: Quando rodando um Java Stackstraces esquisito quando inicializando o `shadow-cljs` ou tentando compilar seus builds você deve ter um conflito de dependências. É muito importante que `shadow-cljs` seja usado com coincidindo as versões do `org.clojure/clojurescript` e `closure-compiler`. É possível chegar isso via `lein deps :tree` e as versões requeridas são listadas no https://clojars.org/thheller/shadow-cljs[clojars] (no lado direito).

==== Rodando Tarefas diretamente a partir do Leiningen

Você deve executar diretamente comando `shadow-cljs` via `lein` se você preferir não usar os comando `shadow-cljs`.

IMPORTANTE: É recomendado ainda usar os comandos `shadow-cljs` para rodar comando desde que isso vai tirar vantagem de uma instância rodando em modo servidor. Isso vai rodar comandos substâncialmente mais rápido que JVM adicionais usando `lein` diretamente.

.Apenas compile modo :dev uma vez, não precisa de REPL ou live-reload:
```bash
$ lein run -m shadow.cljs.devtools.cli compile build-id
```

.Crie um build no modo :release otimizado:
```bash
$ lein run -m shadow.cljs.devtools.cli release build-id
```

=== tools.deps / deps.edn [[deps-edn]]

O novo https://clojure.org/guides/deps_and_cli[deps.edn] pode também ser usado para gerenciar suas `:dependencies` e `:source-paths` ao invés de usar os métodos built-in ou `lein`. Todos os comandos `shadow-cljs` serão então iniciados através do novo `clojure`.

IMPORTANTE: `tools.deps` está mudando muito frequentemente. Tenha certeza que você está usando a última versão.

Para usar isso configure a propriedade `:deps true` em seu config. Também é possível configurar `deps.edn` que deveria ser usadas.

Você deve adicionar o artefator `thheller/shadow-cljs` para seu `deps.edn` manualmente.

.Simples exemplos `shadow-cljs.edn`
```clojure
{:deps true
 :builds ...}
```

.Simples exemplos `deps.edn`
```clojure
{:paths [...]
 :deps {thheller/shadow-cljs {:mvn/version <latest>}}}
```

.Examplo `shadow-cljs.edn` com :cljs 
```clojure
{:deps {:aliases [:cljs]}
 :builds ...}
```

.Examplo `deps.edn`
```clojure
{:paths [...]
 :deps {...}
 :aliases
 {:cljs
  {:extra-deps {thheller/shadow-cljs {:mvn/version <latest>}}}}
```

Rodando diretamente com `clj`.
```
{:paths [...]
 :deps {...}
 :aliases
 {:shadow-cljs
  {:extra-deps {thheller/shadow-cljs {:mvn/version <latest>}}
   :main-opts ["-m" "shadow.cljs.devtools.cli"]}}}
```

```
clj -A:shadow-cljs watch app
```

Você deve especificar apelidos adicionais através da linha de comando usando `-A`, ex. `shadow-cljs -A:foo:bar ...`.

IMPORTANTE: Apelidos são apenas aplicados quando uma nova instância/servidor é iniciado. Eles não aplicam quando conectando a um servidor rodando usando o comando `shadow-cljs`. Rodando através do `clj` vai sempre iniciar uma nova JVM e não suporta o modo servidor.

=== Boot

Os autores tem pouca experiênca com Boot, então nesse capitulo é preciso de contribuidores. Nós entendemos
que Boot permite você construir sua cadeia de ferramentas fora das funções. Desde que `shadow-cljs` e uma 
biblioteca JVM normal, você pode chamar funções internas para invocar tarefas.

Algumas tarefas boot são disponíveis aqui:
https://github.com/jgdavey/boot-shadow-cljs

== Rodando Código Clojure[[clj-run]]

Você pode usar o CLI `shadow-cljs` para chamar funções de Clojure especificas a partir da linha de comando. Isso é útil quando vocie quer rodar algum código antes/depois de certas tarefas. Suponhamos que você queira `rsync` a saída de seu build `release` para um servidor remoto.

.Exemplo de um Namespace Clojure em `src/my/build.clj`
```clojure
(ns my.build
  (:require
    [shadow.cljs.devtools.api :as shadow]
    [clojure.java.shell :refer (sh)]))

(defn release []
  (shadow/release :my-build)
  (sh "rsync" "-arzt" "path/to/output-dir" "my@server.com:some/path"))
```

.Rodando as funções `release`
```bash
$ shadow-cljs clj-run my.build/release
# or
$ shadow-cljs run my.build/release
```

Você pode passar argumentos para funções invocadas através da linha de comando.

.Usando argumento via fn args Clojure
```clojure
...
(defn release [server]
  (shadow/release :my-build)
  (sh "rsync" "-arzt" "path/to/output-dir" server))
```

.Passando o servidor através da linha de comandos
```bash
$ shadow-cljs clj-run my.build/release my@server.com:some/path
```

DICA: A estrutura `(defn release [& args])` também funciona se você quiser parsear os argumentos com alguma coisa como https://github.com/clojure/tools.cli[tools.cli].

Você tem que acessar o poder do Clojure aqui. É possível construir ferramentas no topo disso se você quiser. Como um bônus tudo que você escreve desssa maneira é também diretamente disponível astravés do REPL Clojure.

IMPORTANTE: Quando o <<server-mode, server>> está rodando o namespace não vai ser recarregado automáticamente, isso vai ser carregado apenas uma vez. É recomendado fazer o desenvolviemnto usando uma REPL e recarregando o arquivo (ex: `(require 'my.buid :reload)`). Você deve rodar `shadow-cljs clj-eval "(require 'my.build :reload)"` para recarregar manualmente a partir da linha de comando.

=== Chamando watch através do clj-run

Por padrão as funções chamadas pelo `clj-run` apenas tem acesso ao minimo da runtime `shadow-cljs` da qual é suficiente para rodar o `compile`, `release` e qualquer outra funcionalidade Clojure. A JVM vai terminar quando suas funcões estivem completas.

Se você quer iniciar um `watch` para uma determinada build você precisar declarar que a função que você está chamando requer um servidor completo. Isso vai causar o processo para ficar vivo até você explicitamente chamar o `(shadow.cljs.devtools.server/stop!)` ou `CTRL+C`.

```clojure
(ns demo.run
  (:require [shadow.cljs.devtools.api :as shadow]))

;; this fails because a full server instance is missing
(defn foo
  [& args]
  (shadow/watch :my-build))

;; this metadata will ensure that the server is started so watch works
(defn foo
  {:shadow/requires-server true}
  [& args]
  (shadow/watch :my-build))
```
