= Guia do usuário Shadow CLJS
:author: Thomas Heller and Tony Kay
:revdate: Jan 10, 2018
:revnumber: 1.0
:lang: en
:encoding: UTF-8
:doctype: book
:source-highlighter: coderay
:source-language: clojure
:toc: left
:toclevels: 3
:sectlinks:
:sectanchors:
:leveloffset: 1
:sectnums:
:imagesdir: assets/img
:scriptsdir: js
:imagesoutdir: assets/img

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

ifdef::env-github[]
toc::[]
endif::[]

// TODO: Missing content
// - HUD
// - Undocumented global options
//    - http
//    - ssl
//    - cache-root
//    - open-file-command
//    - others???

include::intro.adoc[]

== Sobre o livro

=== Work in Progress

Está processo de construção. Se você encontrar algum error, por favor nos envie um PR, ou um issue com detalhes do problema.

=== Contribuindo

Os recursos para esse livro estão hospedado em https://github.com/shadow-cljs/shadow-cljs.github.io[Github].

=== Convenções usadas

Existem vários exemplos nesse livro. Muitas coisas usadas aqui deveriam ser óbvia para esse contexto,
mas para prevenir mal-entendidos é importante conhecer as intenções do autor.

Quando exemplos de command-line são dados, devemos incluir comentários BASH (começando com `#`), e
normalmente incluir o padrão de usuário UNIX `$` para indicar separação do comando a partir da saída.

```bash
# Um breve comentário. Esse comando lista arquivos:
$ ls -l
shadow-cljs.edn
project.clj
...
```

Muito dos examples estão no arquivo de configuração do compilador. Esse arquivo contém um mapa EDN. Onde já discutimos opções obrigatórias e iremos frequentemente omitir eles pro questão de clareza. Nesse caso iremos na verdade incluir três pontinhos para indicar "conteúdo é obrigatório mas não é nosso foco atual":

.Exemplo 1. Especificar dependências
```
{:dependencies [[lib "1.0"]]}
```

.Exemplo 2. Adicionar source paths
```
{...
 :source-paths ["src"]
 ...}
```

Isso nos permite incluir contexto suficiente para entender a configuração aninhada:


.Exemplo 3. Opção aninhada
```
{...
 :builds {:build-id {...
                     :output-dir "resources/public/js"}}}
```

Exemplos de código devem ser similarmente encurtados.


= Instalação

== Padrão via `npm`

Você vai precisar:

- https://nodejs.org[`node.js`] (v6.0.0+, ou versões mais recentes)
- https://www.npmjs.com[`npm`] ou https://www.yarnpkg.com[`yarn`]
- Alguma SDK Java (Versão 8 ou superior). http://openjdk.java.net/install/[OpenJDK] ou http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle]

.NPM
```bash
$ npm install --save-dev shadow-cljs
$ npm install -g shadow-cljs
```

.Yarn
```bash
$ yarn add --dev shadow-cljs
$ yarn global add shadow-cljs
```

== Biblioteca

Apesar de ser recomendado rodar a versão padrão via `npm` também é possível embutir `shadow-cljs` em qualquer outra ferramenta JVM (eg. `lein`, `boot`, ...).

O artefato pode ser encontrado em

image::https://img.shields.io/clojars/v/thheller/shadow-cljs.svg[link=https://clojars.org/thheller/shadow-cljs]
image::https://img.shields.io/npm/v/shadow-cljs.svg[link=https://github.com/thheller/shadow-cljs]

include::usage.adoc[]

include::repl.adoc[]

= Configuração [[config]]

`shadow-cljs` é configurado por um arquivo `shadow-cljs.edn` na raíz do projeto. Você pode
criar um template padrão rodando `shadow-cljs init`. Isso deve conter um map com alguma configuração
global e um `:builds`, entrada para todos seus builds.

```
{:source-paths [...]
 :dependencies [...]
 :builds {...}}
```

Um exemplo de configuração poderia parecer tal como:

```clojure
{:dependencies
 [[reagent "0.8.0-alpha2"]]

 :source-paths
 ["src"]

 :builds
 {:app {:target :browser
        :output-dir "public/js"
        :asset-path "/js"
        :modules {:main {:entries [my.app]}}}}}
```

A estrutura desse exemplo poderia parecer com:
```text
.
├── package.json
├── shadow-cljs.edn
└── src
    └── my
        └── app.cljs
```

== Source Paths [[source-paths]]

`:source-paths` configura o classpath da JVM. O compiler vai usar esse config para encontrar arquivos Clojure(Script) (eg `.cljs`).

Está tudo bem colocar qualquer coisa em um source path mas você não pode usar multiplos se você quiser "agrupar" arquivos fonte de uma determinada maneira. É útil se vocie quiser manter seus testes separados por exemplo.

.Using multiple source paths
.Usando multiplos source paths
```
{:source-paths ["src/main" "src/test"]
 ...}
```

.Estrutura de arquivo
```text
.
├── package.json
├── shadow-cljs.edn
└── src
    └── main
        └── my
            └── app.cljs
    └── test
        └── my
            └── app_test.cljs
```

Não é recomendado separar os arquivos fonte por extensão (eg. `src/clj`, `src/cljs`, `src/cljc`). Por alguma razão isso é amplamente usado em projetos CLJS mas isso só deixa as coisas mais difíceis de usar.

== Dependencies

=== Clojure(Script)

As dependência são gerenciadas através da key `:dependencia` na raíz do arquivo de configuração `shadow-cljs.edn`. Utiliza a mesma notação que outras ferramentas Clojure como `lein` e `boot`

Cada dependência é escrita como um vetor usando `[nome-biblioteca "versão"]` aninhados em um vetor exterior.


.Exemplo :dependencies
```clojure
{:source-paths ["src"]
 :dependencies [[reagent "0.9.1"]]
 :builds ...}
```
Perceba que o caminho de origem é *only* especificado apenas uma vez na estrutura. O sistema utilizará grafos de dependência nos namespace para determinar qual código será necessário no final do output para uma determinada build.

=== JavaScript [[npm-install]]

`shadow-cljs` integrates fully with the https://www.npmjs.com/[`npm`] ecosystem to manage JavaScript dependencies.

É possível utilizar `npm` ou `yarn` para gerenciar as dependência, por favor recorra as respectivas documentações.

[horizontal]
npm:: https://docs.npmjs.com/
yarn:: https://yarnpkg.com/en/docs

Ambas gerenciam as dependência através do arquivo `package.json`. Quase sempre o pacote disponível via `npm` vai explicar how instalar ele. Essas instruções agora são aplicadas ao `shadow-cljs` também.

.Instalando um pacote JavaScript
```bash
# npm
$ npm install the-thing

# yarn
$ yarn add the-thing
```

Não é preciso nada mais. As dependências serão adicionadas para o arquivo `package.json` e isso será usado para gerênciar as dependências.

TIP: Se não existe um `package.json` ainda, rode o comando `npm init` a partir do terminal.

==== Ta faltando dependências JS?

Muitas bibliotecas ClojureScript ainda não declaram os pacotes `npm`, ainda usam o <<cljsjs, CLJSJS>>. Nós queremos usar `npm` diretamente o que significa que você deve instalar manualmente os pacotes `npm` até as bibliotecas declararem o `:npm-deps`.

```text
The required JS dependency "react" is not available, it was required by ...
```

Isso significa que você deve instalar o React `npm install react`.

TIP: Nesse caso do `react`, é necessário esses três pacotes: `npm install react react-dom create-react-class`.

== Configuração do usuário [[user-config]]

A maioria das configurações serão feitas no projeto de maneira automática através do `shadow-cljs.edn` mas algumas configurações devem ser user-dependent. Ferramentas como https://docs.cider.mx[CIDER] deve solicitar a dependência adicional `cider-nrepl` da qual seria inútil para a pessoa que usar Cursive quando adicionando essa dependência via `shadow-cljs.edn`.
 
Um restrito conjunto de opções configuração pode ser adicionado para `~/.shadow-cljs/config.edn`dos quais vai aplicar para todos os projetos construídos nessa máquina.

Adicionar dependência é permitido via a key `:dependencies`. Perceba que as dependências adicionadas aqui serão aplicadas a TODOS os projetos. Mantenha só os pacotes relacionados as dependências aqui. Tudo que é relevante a build deve permanecer em `shadow-cljs.edn` de outra maneira as coisas não serão compiladas pra outros usuários.
Essas dependências serão automaticamente ser adicionadas quando usando `deps.edn` ou `lein` também.

.Exemplo ~/.shadow-cljs/config.edn
```
{:dependencies
 [[cider/cider-nrepl "0.21.1"]]}
;; this version may be out of date, check whichever is available
```

Quando usando `deps.edn` para resolver dependências você deve querer algumas vezes ativar apelidos adicionais. Isso pode ser feito através `:deps-aliases`.

```
;; shadow-cljs.edn in project
{:deps {:aliases [:cljs]}}

;; ~/.shadow-cljs/config.edn
{:deps-aliases [:cider]}
```
Isso vai fazer o comando `shadow-cljs` usar o apelido `[:cider :cljs]` no projeto usando `deps.edn`. Isso deve ser útil se você tem um apelido adicional `:cider` no seu `~/.clojure/deps.edn`.

Por padrão o server-mode `shadow-cljs` lançará o servidor nREPL embedado do qual você não precisa. É possível desabilitar essa configuração `:nrepl false` nas configurações de usuário.  

O outro valor aceito para a configuração de usuário é o <<open-file-command, :open-file-command>>. Nenhuma outra opção atualmente terá um efeito aqui.

== Server Options

Essa sessão é para as outras opções que configura a instância do servidor `shadow-cljs`. É opcional.

=== nREPL [[nREPL]]

O `shadow-cljs` <<server-mode, server>> provê um servidor https://nrepl.org[nREPL] via TPC. Se você olhar a mensagem de startup você vera a porta do nREPL, e a porta também está salva no `target/shadow-cljs/nrepl.port`:

```bash
$ shadow-cljs watch app
shadow-cljs - HTTP server available at http://localhost:8600
shadow-cljs - server version: <version> running at http://localhost:9630
shadow-cljs - nREPL server started on port 64967
shadow-cljs - watching build :app
[:app] Configuring build.
[:app] Compiling ...
```

É possível configurar a porta e o middleware adicional com `shadow-cljs.edn`:

```clojure
{...
 :nrepl {:port 9000
         :middleware []} ; optional list of namespace-qualified symbols
 ...}
```

O arquivo de configuração padrão está em `~/.nrepl/nrepl.edn` ou `.nrepl.edn` também carregado no startup e pode ser usado para configurar o `:middleware`.

Se o popular middleware https://github.com/clojure-emacs/cider-nrepl[cider-nrepl] é encontrado no classpath (incluido no `:dependencies`), será usado automaticamente. Nenhuma configuração adicional é necessária. Pode ser desabilitada pela configuração `:nrepl {:cider false}`.



Você deve configurar o namespace que vai iniciar a aplicação quando conectando pela configuração `:init-ns` na opção `:nrepl`. O padrão para `shadow.user`.

```clojure
{...
 :nrepl {:init-ns my.repl}
 ...}
```

O servidor nREPL pode ser desabilitado configurando `:nrepl false`.

==== Usando nREPL

Quando conectando para o servidor nREPL a conexão sempre inicia como um Clojure REPL. Trocar para um CLJS REPL funciona de maneira semelhante para ao <<cljs-repl, non-nREPL version>>. Primeiro o `watch` para uma determinada build precisa ser iniciada e então nós precisamos selecionar essa build para trocar para a sessão do nREPL atual para que ele build. Depois de selecionar o build tudo será avaliado em ClojureScript ao invés de Clojure.

```repl
(shadow/watch :the-build)
(shadow/repl :the-build)
```

Dica: Use `:cljs/quit` to voltar ao Clojure.

==== Servidor nREPL Embedado

Quando você usa `shadow-cljs` embedado em outra ferramenta que provê o próprio servidor nREPL (eg. `lein`) você precisa configurar o middleware `shadow-cljs`. De outra forma você não será capaz de trocar entre as REPLs CLJ e CLJS.

.Exemplo Leiningen `project.clj`
```clojure
(defproject my-amazing-project "1.0.0"
  ...
  :repl-options
  {:init-ns shadow.user ;; or any of your choosing
   :nrepl-middleware
   [shadow.cljs.devtools.server.nrepl/middleware]}
  ...)
```

Dica: Precisa começar o <<embedded, embedded server>> manualmente antes de usar o CLJS REPL.

=== Socket REPL [[socket-repl]]

Um socket Clojure REPL é iniciado automaticamente em server-mode e usa uma porta randômica por padrão. Ferramentas podem encontrar a porta que foi iniciada checando `.shadow-cljs/socket-repl.port` do qual vai conter o número da porta.

É possível configurar uma porta fixa através do `shadow-cljs.edn`.

```clojure
{...
 :socket-repl
 {:port 9000}
 ...}
```

O Socket REPL pode ser desabilitado pela configuração `:socket-repl false`.

=== SSL

O servidor HTTP `shadow-cljs` suporta SSL. Ele requer uma Keystore Java que provê uma chave privada e certificado.

.`shadow-cljs.edn` com SSL configurado
```
{...
 :ssl {:keystore "ssl/keystore.jks"
       :password "shadow-cljs"}
 ...}
```

O exemplo acima são padrão então se você quiser usar ele, tudo bem apenasar configurar `:ssl {}`.

É possível criar uma Keystore usando o comando java `keytool`. Criando um certificado self-signed é também possível mas um pouco complicado.

- https://gist.github.com/jchandra74/36d5f8d0e11960dd8f80260801109ab0[OpenSSL] instruções para Linux e Windows (via WSL)
- https://certsimple.com/blog/localhost-ssl-fix[macOS] instruções

O certificado criado `Certificates.p12` (macOS) ou `localhost.pfx` (Linux, Windows) pode ser ligado dentro do requerido `keystore.jks` através do `keytool`.

```bash
$ keytool -importkeystore -destkeystore keystore.jks -srcstoretype PKCS12 -srckeystore localhost.pfx
```

IMPORTANTE: Você deve gerar o Certificado com a SAN (Subject Alternative Name) para "localhost" (ou qualquer que seja que você quer usar). SAN é obrigatório para Chrome para o Certificado confiável e não mostra alertas. A senha usada quando exportando deve combinar a senha assinada para o Keystore.

// TODO: guia completo, outras plataformas

=== HTTP(S) Primário [[http]]

O servidor `shadow-cljs` inicia em um servidor primário HTTP. Ele é usado para prover a UI e o websocket usado para o Hot Reload e clientes REPL. Por padrão ele escuta a porta 9630. Se essa porta está em uso ela vai incrementar com mais uma tentativa até encontrar uma porta livre.

.Mensagem de Startup para a porta sendo usada
```bash
shadow-cljs - server running at http://0.0.0.0:9630
```

Quando o `:ssl` é configurado, o servidor será avaliado via `https://` ao invés.

DICA: O servidor automáticamente suporta HTTP/2 quando usando `:ssl`.

Se você preferir enviar sua própria porta ao invés, é possível fazer isso via a configuração `:http`.

.`shadow-cljs.edn` com a configuração `:http`
```
{...
 :http {:port 12345
        :host "my.machine.local"}
 ...}
```

`:ssl` troca apenas entre servidores `:https://`. Se você quiser manter a versão `http://` você pode configurar um `:ssl-port` separado também.

```
{...
 :http {:port 12345
        :ssl-port 23456
        :host "localhost"}
 ...}
```

=== Desenvolvimento HTTP(S) [[dev-http]]

`shadow-cljs` consegue provê servidores HTTP adicionais através da configuração `:dev-http`. Por padrão isso vai servir todos os arquivos estáticos a partir do path configurado, e um fall bak para o `index.html` quando o recurso não é encontrado (isso é oque tipicamente queremos quando desenvolvendo uma aplicaçnao do qual usa browser push state).

Esses servidors são iniciados automáticamente quando `shadow-cljs` esta rodando em modo servidor. Eles não são espcficos para alguma build e pode ser usado para servir arquivos de multiplos builds enquanto um único `:output-dir` é usado para cada um.

IMPORTANTE:: Esses são apenas servidores web genéricos que serve arquivos estáticos. Não é requerido para qualquer live-reload ou lógica REPL. Qualquer webserver vai funcionar, esse são fornecidos apenas por conveniência.

.Exemplo básico servindo o diretório `public` através `http://localhost:8000`
```
{...
 :dev-http {8000 "public"}
 :builds {...}}
```

`:dev-http` espera um mapa com `port-number` para o `config`. O `config` suporta vários atalhos para os cenários mais comuns.

.Serve o diretório a apartir do filesystem raíz
```
:dev-http {8000 "public"}
```

.Serve a partir do classpath raíz
```
:dev-http {8000 "classpath:public"}
```

Esse por sua vez, tentaria encontra uma request para `/index.html` através `public/index.html` no classpath. Do qual deve incluir arquivos nos arquivos `.jar`.

.Serve múltiplos roots
```
:dev-http {8000 ["a" "b" "classpath:c"]}
```

Isso deveria primeiro tentar encontrar `<project-root>/a/index.html` e então `<project-root>/b/index.html` e por último `c/index.html` no classpath. Se nenhum dos três for encontrado o comportamento padrão será chamado.

A versão de configuração mais longa espera um mapa e as opções suportadas são:

`:root`:: (String) O caminho serve as requisições. Paths começando com `classpath:` vão servir a partir do classpath ao invés do filesystem. Todos os caminhos do filesystem são relativos ao projeto raíz.
`:roots`:: (Vector of Strings) Se você precisa múltiplos caminhos raíz, ao invés use `root`.
`:ssl-port`:: Quando `:ssl` is configurado, use essa porta para conexões ssl e fornecer HTTP na porta padrão. Se `:ssl-port` não é configurado mas `:ssl` é configurado, a porta padrão vai servir apensas requisições SSL.
`:host`:: Opcional. O hostname a ouvir. Padrão é localhost.
`:handle`:: Opcional. Um totalmente symbol qualificado. Um `(defn handler [req] resp)` que é usado se um recurso não é enconrtado para uma determinada request. Padrão para `shadow.http.push-state/handle`.

As seguintes duas opções são apenas aplicadas quando usando a padrão, construida no handler e tipicamente não precisa ser apenas modificada:

`:push-state/headers`:: (opcional) Um mapa de headers HTTP. Padrão para `text/html` padrão headers.
`:push-state/index`:: (opcional) O arquivo para incial a servir. Padrão para `index.html`.


```clojure
{...
 :dev-http
 {8080 {:root "public"
        :handler my.app/handler}}}
```

==== Suporte a Proxy Reverso [[dev-http-proxy]]

Por padrão o servidor de dev vai tentar servir as requests localmente mas algumas vezes vocie quer usar um servidor web externo para servir as requests (eg. API request). Isso pode ser configurado via `:proxy-url`.

```
{...
 :dev-http
 {8000
  {:root "public"
   :proxy-url "https://some.host"}}}
```

Uma requisição para `http://localhost:8000/api/foo` vai servir o conteúdo retornado por `https://some.host/api/foo`. Todas as requisições que não tem um arquivo local vai ser servido pelo servidor proxied.

Opções Adicionais para configurar o manipulador de conexão são:
[Horizontal]
`:proxy-rewrite-host-header`:: boolean, padrão é true. Determina se o Host original vai ser usado ou um apartir do `:proxy-url`. `localhost` vs `some.host` usando o exemplo acima.
`:proxy-reuse-x-forwarded`:: boolean, padrão é falso. Configura se o proxy deveria adicionar se próprio para a lista `X-Forwarded-For` ou começar um novo.
`:proxy-max-connetion-retries`:: int, padrão para 1.
`:proxy-max-request-time`:: ms como int, padrão para 30000. 30 segundos request timeout.

== Configuração da JVM [[jvm-opts]]
Quando `shadow-cljs.edn` é usado no comando de partida, a JVM pode configurar argumentos de linha de comando adicionais para ser passado diretamente para a JVM. Por exemplo, você quer diminuir ou aumentar a quantidade de memória RAM usada pelo shadow-cljs. 

Isso é feito apenas configurando `:jvm-opts` na raíz do `shadow-cljs.edn` esperando um vetor de strings.

.Exemplo limitando RAM para usar 1GB
```clojure
{:source-paths [...]
 :dependencies [...]
 :jvm-opts ["-Xmx1G"]
 :builds ...}
```

Os argumentos que podem ser passado para a JVM varia dependendo da versão mas é possível encontrar uma lista de exemplos https://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html[here]. Por favor perceba que atribuir muita ou poca RAM pode prejudicar o desempenho. O padrão é bom o suficiente.

IMPORTANTE: Quando usando `deps.edn` ou `project.clj` o `:jvm-opts` precisa ser configurado.

= Configuração de Build

include::build-config.adoc[]

= Navegador como alvo [[target-browser]]

include::target-browser.adoc[]

= React Native como alvo [[target-react-native]]

include::target-react-native.adoc[]

= Node.js como alvo [[target-node]]

Existe suport built-in para geraçnao de código que é pretendido ser usado como um script stand-alone,
e também para o código que é esperado ser usado como uma biblioteca. Veja a sessão
em <<config,common configuration>> para a configuração base
necessaria no arquivo de configuração.

== node.js Scripts [[target-node-script]]

include::target-node-script.adoc[]

== node.js Libraries [[target-node-library]]

include::target-node-library.adoc[]


== Criando pacotes `npm`

// TODO: Thomas: Eu acho que seria útil mostrar um package.json e trecho de um exemplo
// em como você poderia configurar um deploy desses no NPM.

= Embedando em uma ecossistema JS -- O alvo `:npm-module` [[target-npm-module]]

include::target-npm-module.adoc[]

= Testando

`shadow-cljs` provê alguns destinos de utilidade para tornar a construção de testar um pouco mais simples.

Todos os testes geram um test runner e automáticamente combinar todos os namcespace para ser configuravel `:ns-regexp`. O padrão para test runners eram construídos para `cljs.test` mas você consegue criar runners customizaveis se você preferir para usar outros frameworks de teste.

O padrão `:ns-regexp` é `"-test$"`, então seu primeiro test deveria paracer com:

.Arquivo: `src/test/demo/app_test.cljs`
```clojure
(ns demo.app-test
  (:require [cljs.test :refer (deftest is)]))

(deftest a-failing-test
  (is (= 1 2)))
```

No mundo Clojure é comum manter os arquivos de test em seu próprio caminho de origem então o exemplo assume que você tem configurado o `:source-paths ["src/main" "src/test"]` no seu arquivo `shadow-cljs.edn`. Geralmente o código do aplicativo vai dentro de `src/main` e os testes dentro `src/test`. Isso contudo é opcional e esta tudo bem manter tudo dentro de `src` e apenas usar `:source-paths ["src"]`.

== Testando em node.js [[target-node-test]]

include::target-node-test.adoc[]

== Testando no navegador [[target-browser-test]]

include::target-browser-test.adoc[]

== Alvo de testes com Karma para Integração Contínua [[target-karma]]

include::target-karma.adoc[]

= Integração JavaScript [[js-deps]]

include::js-deps.adoc[]

= Gerando código de produção -- Todos os alvos [[release]]

include::release.adoc[]

= Integração com o Editor

include::editor-integration.adoc[]

include::repl-troubleshoot.adoc[]

include::maven-publish.adoc[]

= O que fazer quando as coisas não funcionam?

Desde que o mundo do JS ainda está evoluindo e nem todos estão usando a mesma maneira para escrever e
distribuir código existem algumas coisas em `shadow-cljs` que não funcionam de maneira automática. Essas
coisa podem geralmente ser resolvidas com `:resolve` configs, mas também pode existir bugs ou descuidos.

Se você não consegue resolver um problema com as instruções no capitulo, então tente perguntar no 
https://clojurians.slack.com/messages/C6N245JGG[`#shadow-cljs` Slack channel].

= Hacking

== Patching Libraries

O compilador `shadow-cljs`garanti que as coisas em seu source paths são compiladas primeiro, sobrescrevendo arquivos a partir de JARs. Isso significa que é possível copiar um arquivo fonte a partir de uma bibliotéca, modificar, e incluir isso em seus próprio diretório fonte.

Essa é a maneira conveninente para testar ou corrigir (mesmo para o próprio`shadow-cljs`) em precisar clonar o projeto e entender seu setup, build, etc.
